//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcceptDisputeRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcceptDisputeRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.visa.com/ROLSI}VisaCaseNumber"/>
 *         &lt;element name="AcceptItemID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}AcceptItemType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcceptDisputeRequestType", propOrder = {
    "visaCaseNumber",
    "acceptItemID",
    "acceptItemType"
})
public class AcceptDisputeRequestType {

    @XmlElement(name = "VisaCaseNumber")
    protected long visaCaseNumber;
    @XmlElement(name = "AcceptItemID")
    protected long acceptItemID;
    @XmlElement(name = "AcceptItemType")
    protected String acceptItemType;

    /**
     * Gets the value of the visaCaseNumber property.
     * 
     */
    public long getVisaCaseNumber() {
        return visaCaseNumber;
    }

    /**
     * Sets the value of the visaCaseNumber property.
     * 
     */
    public void setVisaCaseNumber(long value) {
        this.visaCaseNumber = value;
    }

    /**
     * Gets the value of the acceptItemID property.
     * 
     */
    public long getAcceptItemID() {
        return acceptItemID;
    }

    /**
     * Sets the value of the acceptItemID property.
     * 
     */
    public void setAcceptItemID(long value) {
        this.acceptItemID = value;
    }

    /**
     * Gets the value of the acceptItemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptItemType() {
        return acceptItemType;
    }

    /**
     * Sets the value of the acceptItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptItemType(String value) {
        this.acceptItemType = value;
    }

}
