//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AccountingEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountingEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.visa.com/ROLSI}AccountingEntryMemoNumber" minOccurs="0"/>
 *         &lt;element name="AccountingEntryCurrency" type="{http://www.visa.com/ROLSI}CurrencyType"/>
 *         &lt;element name="DisputeAmount" type="{http://www.visa.com/ROLSI}PostingAmountType" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ConsumerAccountNumber" minOccurs="0"/>
 *         &lt;element name="IssuerInstitutionID" type="{http://www.visa.com/ROLSI}TRNType" minOccurs="0"/>
 *         &lt;element name="EntryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="EntryType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="PROVIS"/>
 *               &lt;enumeration value="FINALE"/>
 *               &lt;enumeration value="INILDW"/>
 *               &lt;enumeration value="PFLLDW"/>
 *               &lt;enumeration value="CFLLDW"/>
 *               &lt;enumeration value="WRTOFF"/>
 *               &lt;enumeration value="RELDW"/>
 *               &lt;enumeration value="OTHER"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ConsumerDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PostingAmount" type="{http://www.visa.com/ROLSI}PostingAmountType" minOccurs="0"/>
 *         &lt;element name="GLEntry" type="{http://www.visa.com/ROLSI}GLEntryType" maxOccurs="unbounded"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountingEntryType", propOrder = {
    "accountingEntryMemoNumber",
    "accountingEntryCurrency",
    "disputeAmount",
    "consumerAccountNumber",
    "issuerInstitutionID",
    "entryDate",
    "entryType",
    "consumerDescription",
    "postingAmount",
    "glEntry",
    "notes"
})
public class AccountingEntryType {

    @XmlElement(name = "AccountingEntryMemoNumber")
    protected Long accountingEntryMemoNumber;
    @XmlElement(name = "AccountingEntryCurrency", required = true)
    protected String accountingEntryCurrency;
    @XmlElement(name = "DisputeAmount")
    protected PostingAmountType disputeAmount;
    @XmlElement(name = "ConsumerAccountNumber")
    protected String consumerAccountNumber;
    @XmlElement(name = "IssuerInstitutionID")
    protected String issuerInstitutionID;
    @XmlElement(name = "EntryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar entryDate;
    @XmlElement(name = "EntryType", required = true)
    protected String entryType;
    @XmlElement(name = "ConsumerDescription")
    protected String consumerDescription;
    @XmlElement(name = "PostingAmount")
    protected PostingAmountType postingAmount;
    @XmlElement(name = "GLEntry", required = true)
    protected List<GLEntryType> glEntry;
    @XmlElement(name = "Notes")
    protected String notes;

    /**
     * @direction:Response
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccountingEntryMemoNumber() {
        return accountingEntryMemoNumber;
    }

    /**
     * Sets the value of the accountingEntryMemoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccountingEntryMemoNumber(Long value) {
        this.accountingEntryMemoNumber = value;
    }

    /**
     * Gets the value of the accountingEntryCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingEntryCurrency() {
        return accountingEntryCurrency;
    }

    /**
     * Sets the value of the accountingEntryCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingEntryCurrency(String value) {
        this.accountingEntryCurrency = value;
    }

    /**
     * Gets the value of the disputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link PostingAmountType }
     *     
     */
    public PostingAmountType getDisputeAmount() {
        return disputeAmount;
    }

    /**
     * Sets the value of the disputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostingAmountType }
     *     
     */
    public void setDisputeAmount(PostingAmountType value) {
        this.disputeAmount = value;
    }

    /**
     * Gets the value of the consumerAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerAccountNumber() {
        return consumerAccountNumber;
    }

    /**
     * Sets the value of the consumerAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerAccountNumber(String value) {
        this.consumerAccountNumber = value;
    }

    /**
     * Gets the value of the issuerInstitutionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerInstitutionID() {
        return issuerInstitutionID;
    }

    /**
     * Sets the value of the issuerInstitutionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerInstitutionID(String value) {
        this.issuerInstitutionID = value;
    }

    /**
     * Gets the value of the entryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntryDate() {
        return entryDate;
    }

    /**
     * Sets the value of the entryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntryDate(XMLGregorianCalendar value) {
        this.entryDate = value;
    }

    /**
     * Gets the value of the entryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryType() {
        return entryType;
    }

    /**
     * Sets the value of the entryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryType(String value) {
        this.entryType = value;
    }

    /**
     * Gets the value of the consumerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerDescription() {
        return consumerDescription;
    }

    /**
     * Sets the value of the consumerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerDescription(String value) {
        this.consumerDescription = value;
    }

    /**
     * Gets the value of the postingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link PostingAmountType }
     *     
     */
    public PostingAmountType getPostingAmount() {
        return postingAmount;
    }

    /**
     * Sets the value of the postingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostingAmountType }
     *     
     */
    public void setPostingAmount(PostingAmountType value) {
        this.postingAmount = value;
    }

    /**
     * Gets the value of the glEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the glEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGLEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GLEntryType }
     * 
     * 
     */
    public List<GLEntryType> getGLEntry() {
        if (glEntry == null) {
            glEntry = new ArrayList<GLEntryType>();
        }
        return this.glEntry;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
