//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountingEntryResponseBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountingEntryResponseBodyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}ResponseBodyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="AccountingEntryResponse" type="{http://www.visa.com/ROLSI}AccountingEntryResponseType"/>
 *           &lt;element name="AccountingEntryDetailsResponse" type="{http://www.visa.com/ROLSI}AccountingEntryDetailsResponseType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountingEntryResponseBodyType", propOrder = {
    "accountingEntryResponse",
    "accountingEntryDetailsResponse"
})
public class AccountingEntryResponseBodyType
    extends ResponseBodyType
{

    @XmlElement(name = "AccountingEntryResponse")
    protected AccountingEntryResponseType accountingEntryResponse;
    @XmlElement(name = "AccountingEntryDetailsResponse")
    protected AccountingEntryDetailsResponseType accountingEntryDetailsResponse;

    /**
     * Gets the value of the accountingEntryResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingEntryResponseType }
     *     
     */
    public AccountingEntryResponseType getAccountingEntryResponse() {
        return accountingEntryResponse;
    }

    /**
     * Sets the value of the accountingEntryResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingEntryResponseType }
     *     
     */
    public void setAccountingEntryResponse(AccountingEntryResponseType value) {
        this.accountingEntryResponse = value;
    }

    /**
     * Gets the value of the accountingEntryDetailsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingEntryDetailsResponseType }
     *     
     */
    public AccountingEntryDetailsResponseType getAccountingEntryDetailsResponse() {
        return accountingEntryDetailsResponse;
    }

    /**
     * Sets the value of the accountingEntryDetailsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingEntryDetailsResponseType }
     *     
     */
    public void setAccountingEntryDetailsResponse(AccountingEntryDetailsResponseType value) {
        this.accountingEntryDetailsResponse = value;
    }

}
