//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdviceItemDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdviceItemDetailsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}FormatUQueueItemType">
 *       &lt;sequence>
 *         &lt;element name="DiffBetweenQnAndVDASAdvice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdviceItemDetailsType", propOrder = {
    "diffBetweenQnAndVDASAdvice"
})
public class AdviceItemDetailsType
    extends FormatUQueueItemType
{

    @XmlElement(name = "DiffBetweenQnAndVDASAdvice")
    protected String diffBetweenQnAndVDASAdvice;

    /**
     * Gets the value of the diffBetweenQnAndVDASAdvice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiffBetweenQnAndVDASAdvice() {
        return diffBetweenQnAndVDASAdvice;
    }

    /**
     * Sets the value of the diffBetweenQnAndVDASAdvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiffBetweenQnAndVDASAdvice(String value) {
        this.diffBetweenQnAndVDASAdvice = value;
    }

}
