//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardholderContactInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardholderContactInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContactNamePrefix" type="{http://www.visa.com/ROLSI}CardholderPrefixType" minOccurs="0"/>
 *         &lt;element name="ContactFirstName" type="{http://www.visa.com/ROLSI}CardholderNameType" minOccurs="0"/>
 *         &lt;element name="ContactLastName" type="{http://www.visa.com/ROLSI}CardholderLastNameType" minOccurs="0"/>
 *         &lt;element name="ContactInitial" type="{http://www.visa.com/ROLSI}CardHolderInitialType" minOccurs="0"/>
 *         &lt;element name="BusinessName" type="{http://www.visa.com/ROLSI}BusinessNameType" minOccurs="0"/>
 *         &lt;element name="ContactSuffix" type="{http://www.visa.com/ROLSI}CardHolderSuffixType" minOccurs="0"/>
 *         &lt;element name="NameType" type="{http://www.visa.com/ROLSI}NameValueType" minOccurs="0"/>
 *         &lt;element name="ContactPhone" type="{http://www.visa.com/ROLSI}CardHolderPhoneNumType" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ContactBusinessPhone" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ContactCellPhone" minOccurs="0"/>
 *         &lt;element name="ContactEmail" type="{http://www.visa.com/ROLSI}CardHolderEmailType" minOccurs="0"/>
 *         &lt;element name="ContactFax" type="{http://www.visa.com/ROLSI}ContactFaxType" minOccurs="0"/>
 *         &lt;element name="ContactOther" type="{http://www.visa.com/ROLSI}ContactFaxType" minOccurs="0"/>
 *         &lt;element name="ContactAddress" type="{http://www.visa.com/ROLSI}CardHolderAddressType" minOccurs="0"/>
 *         &lt;element name="ContactAddress2" type="{http://www.visa.com/ROLSI}CardHolderAddressType" minOccurs="0"/>
 *         &lt;element name="ContactAddress3" type="{http://www.visa.com/ROLSI}CardHolderAddressType" minOccurs="0"/>
 *         &lt;element name="ContactCity" type="{http://www.visa.com/ROLSI}CardHolderCityType" minOccurs="0"/>
 *         &lt;element name="ContactStateCode" type="{http://www.visa.com/ROLSI}StateType" minOccurs="0"/>
 *         &lt;element name="Region" type="{http://www.visa.com/ROLSI}ContactRegionType" minOccurs="0"/>
 *         &lt;element name="ContactPostalCode" type="{http://www.visa.com/ROLSI}CardHolderPostalCodeType" minOccurs="0"/>
 *         &lt;element name="ContactCountryCode" type="{http://www.visa.com/ROLSI}CardHolderCountryCodeType" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ContactBestTimeToCall" minOccurs="0"/>
 *         &lt;element name="CardholderOptInInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardholderContactInfoType", propOrder = {
    "contactNamePrefix",
    "contactFirstName",
    "contactLastName",
    "contactInitial",
    "businessName",
    "contactSuffix",
    "nameType",
    "contactPhone",
    "contactBusinessPhone",
    "contactCellPhone",
    "contactEmail",
    "contactFax",
    "contactOther",
    "contactAddress",
    "contactAddress2",
    "contactAddress3",
    "contactCity",
    "contactStateCode",
    "region",
    "contactPostalCode",
    "contactCountryCode",
    "contactBestTimeToCall",
    "cardholderOptInInd"
})
public class CardholderContactInfoType {

    @XmlElement(name = "ContactNamePrefix")
    protected String contactNamePrefix;
    @XmlElement(name = "ContactFirstName")
    protected String contactFirstName;
    @XmlElement(name = "ContactLastName")
    protected String contactLastName;
    @XmlElement(name = "ContactInitial")
    protected String contactInitial;
    @XmlElement(name = "BusinessName")
    protected String businessName;
    @XmlElement(name = "ContactSuffix")
    protected String contactSuffix;
    @XmlElement(name = "NameType")
    @XmlSchemaType(name = "string")
    protected NameValueType nameType;
    @XmlElement(name = "ContactPhone")
    protected String contactPhone;
    @XmlElement(name = "ContactBusinessPhone")
    protected String contactBusinessPhone;
    @XmlElement(name = "ContactCellPhone")
    protected String contactCellPhone;
    @XmlElement(name = "ContactEmail")
    protected String contactEmail;
    @XmlElement(name = "ContactFax")
    protected String contactFax;
    @XmlElement(name = "ContactOther")
    protected String contactOther;
    @XmlElement(name = "ContactAddress")
    protected String contactAddress;
    @XmlElement(name = "ContactAddress2")
    protected String contactAddress2;
    @XmlElement(name = "ContactAddress3")
    protected String contactAddress3;
    @XmlElement(name = "ContactCity")
    protected String contactCity;
    @XmlElement(name = "ContactStateCode")
    protected String contactStateCode;
    @XmlElement(name = "Region")
    protected String region;
    @XmlElement(name = "ContactPostalCode")
    protected String contactPostalCode;
    @XmlElement(name = "ContactCountryCode")
    protected String contactCountryCode;
    @XmlElement(name = "ContactBestTimeToCall")
    protected String contactBestTimeToCall;
    @XmlElement(name = "CardholderOptInInd")
    protected Boolean cardholderOptInInd;

    /**
     * Gets the value of the contactNamePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactNamePrefix() {
        return contactNamePrefix;
    }

    /**
     * Sets the value of the contactNamePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactNamePrefix(String value) {
        this.contactNamePrefix = value;
    }

    /**
     * Gets the value of the contactFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactFirstName() {
        return contactFirstName;
    }

    /**
     * Sets the value of the contactFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactFirstName(String value) {
        this.contactFirstName = value;
    }

    /**
     * Gets the value of the contactLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactLastName() {
        return contactLastName;
    }

    /**
     * Sets the value of the contactLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactLastName(String value) {
        this.contactLastName = value;
    }

    /**
     * Gets the value of the contactInitial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactInitial() {
        return contactInitial;
    }

    /**
     * Sets the value of the contactInitial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactInitial(String value) {
        this.contactInitial = value;
    }

    /**
     * Gets the value of the businessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * Sets the value of the businessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessName(String value) {
        this.businessName = value;
    }

    /**
     * Gets the value of the contactSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactSuffix() {
        return contactSuffix;
    }

    /**
     * Sets the value of the contactSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactSuffix(String value) {
        this.contactSuffix = value;
    }

    /**
     * Gets the value of the nameType property.
     * 
     * @return
     *     possible object is
     *     {@link NameValueType }
     *     
     */
    public NameValueType getNameType() {
        return nameType;
    }

    /**
     * Sets the value of the nameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameValueType }
     *     
     */
    public void setNameType(NameValueType value) {
        this.nameType = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the contactBusinessPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactBusinessPhone() {
        return contactBusinessPhone;
    }

    /**
     * Sets the value of the contactBusinessPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactBusinessPhone(String value) {
        this.contactBusinessPhone = value;
    }

    /**
     * Gets the value of the contactCellPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCellPhone() {
        return contactCellPhone;
    }

    /**
     * Sets the value of the contactCellPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCellPhone(String value) {
        this.contactCellPhone = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the contactFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactFax() {
        return contactFax;
    }

    /**
     * Sets the value of the contactFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactFax(String value) {
        this.contactFax = value;
    }

    /**
     * Gets the value of the contactOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactOther() {
        return contactOther;
    }

    /**
     * Sets the value of the contactOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactOther(String value) {
        this.contactOther = value;
    }

    /**
     * Gets the value of the contactAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * Sets the value of the contactAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddress(String value) {
        this.contactAddress = value;
    }

    /**
     * Gets the value of the contactAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddress2() {
        return contactAddress2;
    }

    /**
     * Sets the value of the contactAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddress2(String value) {
        this.contactAddress2 = value;
    }

    /**
     * Gets the value of the contactAddress3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddress3() {
        return contactAddress3;
    }

    /**
     * Sets the value of the contactAddress3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddress3(String value) {
        this.contactAddress3 = value;
    }

    /**
     * Gets the value of the contactCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCity() {
        return contactCity;
    }

    /**
     * Sets the value of the contactCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCity(String value) {
        this.contactCity = value;
    }

    /**
     * Gets the value of the contactStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactStateCode() {
        return contactStateCode;
    }

    /**
     * Sets the value of the contactStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactStateCode(String value) {
        this.contactStateCode = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the contactPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPostalCode() {
        return contactPostalCode;
    }

    /**
     * Sets the value of the contactPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPostalCode(String value) {
        this.contactPostalCode = value;
    }

    /**
     * Gets the value of the contactCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCountryCode() {
        return contactCountryCode;
    }

    /**
     * Sets the value of the contactCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCountryCode(String value) {
        this.contactCountryCode = value;
    }

    /**
     * Gets the value of the contactBestTimeToCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactBestTimeToCall() {
        return contactBestTimeToCall;
    }

    /**
     * Sets the value of the contactBestTimeToCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactBestTimeToCall(String value) {
        this.contactBestTimeToCall = value;
    }

    /**
     * Gets the value of the cardholderOptInInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCardholderOptInInd() {
        return cardholderOptInInd;
    }

    /**
     * Sets the value of the cardholderOptInInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCardholderOptInInd(Boolean value) {
        this.cardholderOptInInd = value;
    }

}
