//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseFilingItemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CaseFilingItemType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FilingLetter"/>
 *     &lt;enumeration value="ContactMessage"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CaseFilingItemType")
@XmlEnum
public enum CaseFilingItemType {

    @XmlEnumValue("FilingLetter")
    FILING_LETTER("FilingLetter"),
    @XmlEnumValue("ContactMessage")
    CONTACT_MESSAGE("ContactMessage");
    private final String value;

    CaseFilingItemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CaseFilingItemType fromValue(String v) {
        for (CaseFilingItemType c: CaseFilingItemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
