//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CreditMultiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditMultiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CreditDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CreditAmount" type="{http://www.visa.com/ROLSI}AmountType" minOccurs="0"/>
 *         &lt;element name="MatchingCreditTranId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="CreditARN" type="{http://www.visa.com/ROLSI}ARNType" minOccurs="0"/>
 *         &lt;element name="CreditTransactionID" type="{http://www.visa.com/ROLSI}TranIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditMultiType", propOrder = {
    "creditDate",
    "creditAmount",
    "matchingCreditTranId",
    "creditARN",
    "creditTransactionID"
})
public class CreditMultiType {

    @XmlElement(name = "CreditDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creditDate;
    @XmlElement(name = "CreditAmount")
    protected AmountType creditAmount;
    @XmlElement(name = "MatchingCreditTranId")
    protected Long matchingCreditTranId;
    @XmlElement(name = "CreditARN")
    protected String creditARN;
    @XmlElement(name = "CreditTransactionID")
    protected String creditTransactionID;
    @XmlAttribute(name = "id")
    protected BigInteger id;

    /**
     * Gets the value of the creditDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreditDate() {
        return creditDate;
    }

    /**
     * Sets the value of the creditDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreditDate(XMLGregorianCalendar value) {
        this.creditDate = value;
    }

    /**
     * Gets the value of the creditAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getCreditAmount() {
        return creditAmount;
    }

    /**
     * Sets the value of the creditAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setCreditAmount(AmountType value) {
        this.creditAmount = value;
    }

    /**
     * Gets the value of the matchingCreditTranId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMatchingCreditTranId() {
        return matchingCreditTranId;
    }

    /**
     * Sets the value of the matchingCreditTranId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMatchingCreditTranId(Long value) {
        this.matchingCreditTranId = value;
    }

    /**
     * Gets the value of the creditARN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditARN() {
        return creditARN;
    }

    /**
     * Sets the value of the creditARN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditARN(String value) {
        this.creditARN = value;
    }

    /**
     * Gets the value of the creditTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditTransactionID() {
        return creditTransactionID;
    }

    /**
     * Sets the value of the creditTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditTransactionID(String value) {
        this.creditTransactionID = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
