//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispCancellationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DispCancellationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="R0"/>
 *     &lt;enumeration value="R1A"/>
 *     &lt;enumeration value="R1B"/>
 *     &lt;enumeration value="R3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DispCancellationType")
@XmlEnum
public enum DispCancellationType {

    @XmlEnumValue("R0")
    R_0("R0"),
    @XmlEnumValue("R1A")
    R_1_A("R1A"),
    @XmlEnumValue("R1B")
    R_1_B("R1B"),
    @XmlEnumValue("R3")
    R_3("R3");
    private final String value;

    DispCancellationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DispCancellationType fromValue(String v) {
        for (DispCancellationType c: DispCancellationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
