//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisputeStageType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DisputeStageType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RF"/>
 *     &lt;enumeration value="CB"/>
 *     &lt;enumeration value="RE"/>
 *     &lt;enumeration value="SC"/>
 *     &lt;enumeration value="PD"/>
 *     &lt;enumeration value="IPC"/>
 *     &lt;enumeration value="IPCR"/>
 *     &lt;enumeration value="APC"/>
 *     &lt;enumeration value="APCR"/>
 *     &lt;enumeration value="IPA"/>
 *     &lt;enumeration value="IPAR"/>
 *     &lt;enumeration value="APA"/>
 *     &lt;enumeration value="APAR"/>
 *     &lt;enumeration value="RFC"/>
 *     &lt;enumeration value="ARBACQ"/>
 *     &lt;enumeration value="ARBISS"/>
 *     &lt;enumeration value="COMPACQ"/>
 *     &lt;enumeration value="COMPISS"/>
 *     &lt;enumeration value="MISC"/>
 *     &lt;enumeration value="CORR"/>
 *     &lt;enumeration value="ORGTRN"/>
 *     &lt;enumeration value="WRTOFF"/>
 *     &lt;enumeration value="MSG"/>
 *     &lt;enumeration value="CLB"/>
 *     &lt;enumeration value="DSPT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DisputeStageType")
@XmlEnum
public enum DisputeStageType {

    RF,
    CB,
    RE,
    SC,
    PD,
    IPC,
    IPCR,
    APC,
    APCR,
    IPA,
    IPAR,
    APA,
    APAR,
    RFC,
    ARBACQ,
    ARBISS,
    COMPACQ,
    COMPISS,
    MISC,
    CORR,
    ORGTRN,
    WRTOFF,
    MSG,
    CLB,
    DSPT;

    public String value() {
        return name();
    }

    public static DisputeStageType fromValue(String v) {
        return valueOf(v);
    }

}
