//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisputeFilingRespRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisputeFilingRespRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IssuerAcquirerContactInfo" type="{http://www.visa.com/ROLSI}IssuerAcquirerContactInfoType" minOccurs="0"/>
 *         &lt;element name="RequestToWithdrawInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CaseFilingType" type="{http://www.visa.com/ROLSI}FilingRespTypeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisputeFilingRespRequestType", propOrder = {
    "issuerAcquirerContactInfo",
    "requestToWithdrawInd",
    "caseFilingType"
})
public class DisputeFilingRespRequestType {

    @XmlElement(name = "IssuerAcquirerContactInfo")
    protected IssuerAcquirerContactInfoType issuerAcquirerContactInfo;
    @XmlElement(name = "RequestToWithdrawInd")
    protected Boolean requestToWithdrawInd;
    @XmlElement(name = "CaseFilingType")
    @XmlSchemaType(name = "string")
    protected FilingRespTypeType caseFilingType;

    /**
     * Gets the value of the issuerAcquirerContactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IssuerAcquirerContactInfoType }
     *     
     */
    public IssuerAcquirerContactInfoType getIssuerAcquirerContactInfo() {
        return issuerAcquirerContactInfo;
    }

    /**
     * Sets the value of the issuerAcquirerContactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuerAcquirerContactInfoType }
     *     
     */
    public void setIssuerAcquirerContactInfo(IssuerAcquirerContactInfoType value) {
        this.issuerAcquirerContactInfo = value;
    }

    /**
     * Gets the value of the requestToWithdrawInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestToWithdrawInd() {
        return requestToWithdrawInd;
    }

    /**
     * Sets the value of the requestToWithdrawInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestToWithdrawInd(Boolean value) {
        this.requestToWithdrawInd = value;
    }

    /**
     * Gets the value of the caseFilingType property.
     * 
     * @return
     *     possible object is
     *     {@link FilingRespTypeType }
     *     
     */
    public FilingRespTypeType getCaseFilingType() {
        return caseFilingType;
    }

    /**
     * Sets the value of the caseFilingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilingRespTypeType }
     *     
     */
    public void setCaseFilingType(FilingRespTypeType value) {
        this.caseFilingType = value;
    }

}
