//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisputeResponseReasonType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DisputeResponseReasonType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CNLD"/>
 *     &lt;enumeration value="CE"/>
 *     &lt;enumeration value="CP"/>
 *     &lt;enumeration value="RM"/>
 *     &lt;enumeration value="CDLT"/>
 *     &lt;enumeration value="ID"/>
 *     &lt;enumeration value="NL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DisputeResponseReasonType")
@XmlEnum
public enum DisputeResponseReasonType {

    CNLD,
    CE,
    CP,
    RM,
    CDLT,
    ID,
    NL;

    public String value() {
        return name();
    }

    public static DisputeResponseReasonType fromValue(String v) {
        return valueOf(v);
    }

}
