//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisputeKSourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DisputeKSourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UI"/>
 *     &lt;enumeration value="RTSI"/>
 *     &lt;enumeration value="BulkSI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DisputeKSourceType")
@XmlEnum
public enum DisputeKSourceType {

    UI("UI"),
    RTSI("RTSI"),
    @XmlEnumValue("BulkSI")
    BULK_SI("BulkSI");
    private final String value;

    DisputeKSourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DisputeKSourceType fromValue(String v) {
        for (DisputeKSourceType c: DisputeKSourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
