//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import java.io.Serializable;
import java.util.Date;

import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;


@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(Include.NON_EMPTY)
public class DisputeFraudInfoType implements Serializable {

	private static final long serialVersionUID = -1244848450469795384L;
	
	@JsonProperty("MailDate")
    @JsonFormat(pattern = "yyyy-MM-dd  HH:mm:ss",
	shape = JsonFormat.Shape.STRING,
	locale = "pt-BR",
	timezone = "Brazil/East")
    protected Date mailDate;
    @JsonProperty("MailCity")
    protected String mailCity;
    @JsonProperty("MailStateCode")
    protected String mailStateCode;
    @JsonProperty("ValidFrom")
    protected String validFrom;
    @JsonProperty("MailPostalCode")
    protected String mailPostalCode;
    @JsonProperty("FraudType")
    protected String fraudType;

    /**
     * Gets the value of the mailDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getMailDate() {
        return mailDate;
    }

    /**
     * Sets the value of the mailDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMailDate(Date value) {
        this.mailDate = value;
    }

    /**
     * Gets the value of the mailCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailCity() {
        return mailCity;
    }

    /**
     * Sets the value of the mailCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailCity(String value) {
        this.mailCity = value;
    }

    /**
     * Gets the value of the mailStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailStateCode() {
        return mailStateCode;
    }

    /**
     * Sets the value of the mailStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailStateCode(String value) {
        this.mailStateCode = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidFrom(String value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the mailPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailPostalCode() {
        return mailPostalCode;
    }

    /**
     * Sets the value of the mailPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailPostalCode(String value) {
        this.mailPostalCode = value;
    }

    /**
     * Gets the value of the fraudType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudType() {
        return fraudType;
    }

    /**
     * Sets the value of the fraudType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudType(String value) {
        this.fraudType = value;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fraudType == null) ? 0 : fraudType.hashCode());
		result = prime * result + ((mailCity == null) ? 0 : mailCity.hashCode());
		result = prime * result + ((mailDate == null) ? 0 : mailDate.hashCode());
		result = prime * result + ((mailPostalCode == null) ? 0 : mailPostalCode.hashCode());
		result = prime * result + ((mailStateCode == null) ? 0 : mailStateCode.hashCode());
		result = prime * result + ((validFrom == null) ? 0 : validFrom.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DisputeFraudInfoType other = (DisputeFraudInfoType) obj;
		if (fraudType == null) {
			if (other.fraudType != null)
				return false;
		} else if (!fraudType.equals(other.fraudType))
			return false;
		if (mailCity == null) {
			if (other.mailCity != null)
				return false;
		} else if (!mailCity.equals(other.mailCity))
			return false;
		if (mailDate == null) {
			if (other.mailDate != null)
				return false;
		} else if (!mailDate.equals(other.mailDate))
			return false;
		if (mailPostalCode == null) {
			if (other.mailPostalCode != null)
				return false;
		} else if (!mailPostalCode.equals(other.mailPostalCode))
			return false;
		if (mailStateCode == null) {
			if (other.mailStateCode != null)
				return false;
		} else if (!mailStateCode.equals(other.mailStateCode))
			return false;
		if (validFrom == null) {
			if (other.validFrom != null)
				return false;
		} else if (!validFrom.equals(other.validFrom))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "DisputeFraudInfoType [mailDate=" + mailDate + ", mailCity=" + mailCity + ", mailStateCode="
				+ mailStateCode + ", validFrom=" + validFrom + ", mailPostalCode=" + mailPostalCode + ", fraudType="
				+ fraudType + "]";
	}

}
