//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisputeProcessErrorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisputeProcessErrorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WhatIncorrectAboutTransaction" type="{http://www.visa.com/ROLSI}WhatIncorrectAboutTransactionType" minOccurs="0"/>
 *         &lt;element name="AccountStatus" type="{http://www.visa.com/ROLSI}AccountStatusType" minOccurs="0"/>
 *         &lt;element name="CorrectCurrency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RolTransactionId" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncorrectTransactionId" type="{http://www.visa.com/ROLSI}TranIDType" minOccurs="0"/>
 *         &lt;element name="DuplicateTranId" type="{http://www.visa.com/ROLSI}TranIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TransactionCodeIncorrect" type="{http://www.visa.com/ROLSI}TransactionCodeIncorrectType" minOccurs="0"/>
 *         &lt;element name="IssuerMasterFileAccountNumberInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="CardholderReceiptAccountNumber" type="{http://www.visa.com/ROLSI}AcctNumType" minOccurs="0"/>
 *         &lt;element name="ChipCardContainValidCryptogramInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="ExplainWhyCreditRefundProcessedInError" type="{http://www.visa.com/ROLSI}Desc10000Type" minOccurs="0"/>
 *         &lt;element name="ReceiptAccountNumberMatchInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="PrepaymentPartialTransactionInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="CardholderReceiptAmt" type="{http://www.visa.com/ROLSI}AmountType" minOccurs="0"/>
 *         &lt;element name="MerchantDisputePriceDiffInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="BothTransactionsOnSameAcctNumberInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="IssuerOrCardholderOtherAcctWithDiffVisaCardInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="IssuerEvidenceMerchantPassedOnFundsInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="PrepaymentBalanceNotPaidInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="ProvidingPaymentProofOtherMeans" type="{http://www.visa.com/ROLSI}ProvidingPaymentProofOtherType" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ProcessingErrorOtherExplanation" minOccurs="0"/>
 *         &lt;element name="IncorrectCurrencyReason" type="{http://www.visa.com/ROLSI}IncorrectCurrencyReasonType" minOccurs="0"/>
 *         &lt;element name="AuthorizationRequestDeclinedValidDataInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ExplainWhyValidDataInclusionReason" type="{http://www.visa.com/ROLSI}Desc10000Type" minOccurs="0"/>
 *         &lt;element name="CardholderDidNotAgreeDCC" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="CardholderAttemptToResolve" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="AttemptToResolveProhLocalLaw" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="DetailsOfLocalLaw" type="{http://www.visa.com/ROLSI}Desc10000Type" minOccurs="0"/>
 *         &lt;element name="OtherTranInvolveDiffMerchantInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="OtherTranSameMerchantInd" type="{http://www.visa.com/ROLSI}YNType" minOccurs="0"/>
 *         &lt;element name="TransactionID" type="{http://www.visa.com/ROLSI}TranIDType" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ARN" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisputeProcessErrorType", propOrder = {
    "whatIncorrectAboutTransaction",
    "accountStatus",
    "correctCurrency",
    "rolTransactionId",
    "incorrectTransactionId",
    "duplicateTranId",
    "transactionCodeIncorrect",
    "issuerMasterFileAccountNumberInd",
    "cardholderReceiptAccountNumber",
    "chipCardContainValidCryptogramInd",
    "explainWhyCreditRefundProcessedInError",
    "receiptAccountNumberMatchInd",
    "prepaymentPartialTransactionInd",
    "cardholderReceiptAmt",
    "merchantDisputePriceDiffInd",
    "bothTransactionsOnSameAcctNumberInd",
    "issuerOrCardholderOtherAcctWithDiffVisaCardInd",
    "issuerEvidenceMerchantPassedOnFundsInd",
    "prepaymentBalanceNotPaidInd",
    "providingPaymentProofOtherMeans",
    "processingErrorOtherExplanation",
    "incorrectCurrencyReason",
    "authorizationRequestDeclinedValidDataInd",
    "explainWhyValidDataInclusionReason",
    "cardholderDidNotAgreeDCC",
    "cardholderAttemptToResolve",
    "attemptToResolveProhLocalLaw",
    "detailsOfLocalLaw",
    "otherTranInvolveDiffMerchantInd",
    "otherTranSameMerchantInd",
    "transactionID",
    "arn"
})
public class DisputeProcessErrorType {

    @XmlElement(name = "WhatIncorrectAboutTransaction")
    @XmlSchemaType(name = "string")
    protected WhatIncorrectAboutTransactionType whatIncorrectAboutTransaction;
    @XmlElement(name = "AccountStatus")
    @XmlSchemaType(name = "string")
    protected AccountStatusType accountStatus;
    @XmlElement(name = "CorrectCurrency")
    protected BigInteger correctCurrency;
    @XmlElement(name = "RolTransactionId", type = Long.class)
    protected List<Long> rolTransactionId;
    @XmlElement(name = "IncorrectTransactionId")
    protected String incorrectTransactionId;
    @XmlElement(name = "DuplicateTranId")
    protected List<String> duplicateTranId;
    @XmlElement(name = "TransactionCodeIncorrect")
    @XmlSchemaType(name = "string")
    protected TransactionCodeIncorrectType transactionCodeIncorrect;
    @XmlElement(name = "IssuerMasterFileAccountNumberInd")
    @XmlSchemaType(name = "string")
    protected YNType issuerMasterFileAccountNumberInd;
    @XmlElement(name = "CardholderReceiptAccountNumber")
    protected String cardholderReceiptAccountNumber;
    @XmlElement(name = "ChipCardContainValidCryptogramInd")
    @XmlSchemaType(name = "string")
    protected YNType chipCardContainValidCryptogramInd;
    @XmlElement(name = "ExplainWhyCreditRefundProcessedInError")
    protected String explainWhyCreditRefundProcessedInError;
    @XmlElement(name = "ReceiptAccountNumberMatchInd")
    @XmlSchemaType(name = "string")
    protected YNType receiptAccountNumberMatchInd;
    @XmlElement(name = "PrepaymentPartialTransactionInd")
    @XmlSchemaType(name = "string")
    protected YNType prepaymentPartialTransactionInd;
    @XmlElement(name = "CardholderReceiptAmt")
    protected AmountType cardholderReceiptAmt;
    @XmlElement(name = "MerchantDisputePriceDiffInd")
    @XmlSchemaType(name = "string")
    protected YNType merchantDisputePriceDiffInd;
    @XmlElement(name = "BothTransactionsOnSameAcctNumberInd")
    @XmlSchemaType(name = "string")
    protected YNType bothTransactionsOnSameAcctNumberInd;
    @XmlElement(name = "IssuerOrCardholderOtherAcctWithDiffVisaCardInd")
    @XmlSchemaType(name = "string")
    protected YNType issuerOrCardholderOtherAcctWithDiffVisaCardInd;
    @XmlElement(name = "IssuerEvidenceMerchantPassedOnFundsInd")
    @XmlSchemaType(name = "string")
    protected YNType issuerEvidenceMerchantPassedOnFundsInd;
    @XmlElement(name = "PrepaymentBalanceNotPaidInd")
    @XmlSchemaType(name = "string")
    protected YNType prepaymentBalanceNotPaidInd;
    @XmlElement(name = "ProvidingPaymentProofOtherMeans")
    @XmlSchemaType(name = "string")
    protected ProvidingPaymentProofOtherType providingPaymentProofOtherMeans;
    @XmlElement(name = "ProcessingErrorOtherExplanation")
    protected String processingErrorOtherExplanation;
    @XmlElement(name = "IncorrectCurrencyReason")
    @XmlSchemaType(name = "string")
    protected IncorrectCurrencyReasonType incorrectCurrencyReason;
    @XmlElement(name = "AuthorizationRequestDeclinedValidDataInd")
    protected Boolean authorizationRequestDeclinedValidDataInd;
    @XmlElement(name = "ExplainWhyValidDataInclusionReason")
    protected String explainWhyValidDataInclusionReason;
    @XmlElement(name = "CardholderDidNotAgreeDCC")
    @XmlSchemaType(name = "string")
    protected YNType cardholderDidNotAgreeDCC;
    @XmlElement(name = "CardholderAttemptToResolve")
    @XmlSchemaType(name = "string")
    protected YNType cardholderAttemptToResolve;
    @XmlElement(name = "AttemptToResolveProhLocalLaw")
    @XmlSchemaType(name = "string")
    protected YNType attemptToResolveProhLocalLaw;
    @XmlElement(name = "DetailsOfLocalLaw")
    protected String detailsOfLocalLaw;
    @XmlElement(name = "OtherTranInvolveDiffMerchantInd")
    @XmlSchemaType(name = "string")
    protected YNType otherTranInvolveDiffMerchantInd;
    @XmlElement(name = "OtherTranSameMerchantInd")
    @XmlSchemaType(name = "string")
    protected YNType otherTranSameMerchantInd;
    @XmlElement(name = "TransactionID")
    protected String transactionID;
    @XmlElement(name = "ARN")
    protected String arn;

    /**
     * Gets the value of the whatIncorrectAboutTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link WhatIncorrectAboutTransactionType }
     *     
     */
    public WhatIncorrectAboutTransactionType getWhatIncorrectAboutTransaction() {
        return whatIncorrectAboutTransaction;
    }

    /**
     * Sets the value of the whatIncorrectAboutTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhatIncorrectAboutTransactionType }
     *     
     */
    public void setWhatIncorrectAboutTransaction(WhatIncorrectAboutTransactionType value) {
        this.whatIncorrectAboutTransaction = value;
    }

    /**
     * Gets the value of the accountStatus property.
     * 
     * @return
     *     possible object is
     *     {@link AccountStatusType }
     *     
     */
    public AccountStatusType getAccountStatus() {
        return accountStatus;
    }

    /**
     * Sets the value of the accountStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountStatusType }
     *     
     */
    public void setAccountStatus(AccountStatusType value) {
        this.accountStatus = value;
    }

    /**
     * Gets the value of the correctCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCorrectCurrency() {
        return correctCurrency;
    }

    /**
     * Sets the value of the correctCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCorrectCurrency(BigInteger value) {
        this.correctCurrency = value;
    }

    /**
     * Gets the value of the rolTransactionId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rolTransactionId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRolTransactionId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getRolTransactionId() {
        if (rolTransactionId == null) {
            rolTransactionId = new ArrayList<Long>();
        }
        return this.rolTransactionId;
    }

    /**
     * Gets the value of the incorrectTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncorrectTransactionId() {
        return incorrectTransactionId;
    }

    /**
     * Sets the value of the incorrectTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncorrectTransactionId(String value) {
        this.incorrectTransactionId = value;
    }

    /**
     * Gets the value of the duplicateTranId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the duplicateTranId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDuplicateTranId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDuplicateTranId() {
        if (duplicateTranId == null) {
            duplicateTranId = new ArrayList<String>();
        }
        return this.duplicateTranId;
    }

    /**
     * Gets the value of the transactionCodeIncorrect property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionCodeIncorrectType }
     *     
     */
    public TransactionCodeIncorrectType getTransactionCodeIncorrect() {
        return transactionCodeIncorrect;
    }

    /**
     * Sets the value of the transactionCodeIncorrect property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionCodeIncorrectType }
     *     
     */
    public void setTransactionCodeIncorrect(TransactionCodeIncorrectType value) {
        this.transactionCodeIncorrect = value;
    }

    /**
     * Gets the value of the issuerMasterFileAccountNumberInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getIssuerMasterFileAccountNumberInd() {
        return issuerMasterFileAccountNumberInd;
    }

    /**
     * Sets the value of the issuerMasterFileAccountNumberInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setIssuerMasterFileAccountNumberInd(YNType value) {
        this.issuerMasterFileAccountNumberInd = value;
    }

    /**
     * Gets the value of the cardholderReceiptAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderReceiptAccountNumber() {
        return cardholderReceiptAccountNumber;
    }

    /**
     * Sets the value of the cardholderReceiptAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderReceiptAccountNumber(String value) {
        this.cardholderReceiptAccountNumber = value;
    }

    /**
     * Gets the value of the chipCardContainValidCryptogramInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getChipCardContainValidCryptogramInd() {
        return chipCardContainValidCryptogramInd;
    }

    /**
     * Sets the value of the chipCardContainValidCryptogramInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setChipCardContainValidCryptogramInd(YNType value) {
        this.chipCardContainValidCryptogramInd = value;
    }

    /**
     * Gets the value of the explainWhyCreditRefundProcessedInError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplainWhyCreditRefundProcessedInError() {
        return explainWhyCreditRefundProcessedInError;
    }

    /**
     * Sets the value of the explainWhyCreditRefundProcessedInError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplainWhyCreditRefundProcessedInError(String value) {
        this.explainWhyCreditRefundProcessedInError = value;
    }

    /**
     * Gets the value of the receiptAccountNumberMatchInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getReceiptAccountNumberMatchInd() {
        return receiptAccountNumberMatchInd;
    }

    /**
     * Sets the value of the receiptAccountNumberMatchInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setReceiptAccountNumberMatchInd(YNType value) {
        this.receiptAccountNumberMatchInd = value;
    }

    /**
     * Gets the value of the prepaymentPartialTransactionInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getPrepaymentPartialTransactionInd() {
        return prepaymentPartialTransactionInd;
    }

    /**
     * Sets the value of the prepaymentPartialTransactionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setPrepaymentPartialTransactionInd(YNType value) {
        this.prepaymentPartialTransactionInd = value;
    }

    /**
     * Gets the value of the cardholderReceiptAmt property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getCardholderReceiptAmt() {
        return cardholderReceiptAmt;
    }

    /**
     * Sets the value of the cardholderReceiptAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setCardholderReceiptAmt(AmountType value) {
        this.cardholderReceiptAmt = value;
    }

    /**
     * Gets the value of the merchantDisputePriceDiffInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getMerchantDisputePriceDiffInd() {
        return merchantDisputePriceDiffInd;
    }

    /**
     * Sets the value of the merchantDisputePriceDiffInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setMerchantDisputePriceDiffInd(YNType value) {
        this.merchantDisputePriceDiffInd = value;
    }

    /**
     * Gets the value of the bothTransactionsOnSameAcctNumberInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getBothTransactionsOnSameAcctNumberInd() {
        return bothTransactionsOnSameAcctNumberInd;
    }

    /**
     * Sets the value of the bothTransactionsOnSameAcctNumberInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setBothTransactionsOnSameAcctNumberInd(YNType value) {
        this.bothTransactionsOnSameAcctNumberInd = value;
    }

    /**
     * Gets the value of the issuerOrCardholderOtherAcctWithDiffVisaCardInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getIssuerOrCardholderOtherAcctWithDiffVisaCardInd() {
        return issuerOrCardholderOtherAcctWithDiffVisaCardInd;
    }

    /**
     * Sets the value of the issuerOrCardholderOtherAcctWithDiffVisaCardInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setIssuerOrCardholderOtherAcctWithDiffVisaCardInd(YNType value) {
        this.issuerOrCardholderOtherAcctWithDiffVisaCardInd = value;
    }

    /**
     * Gets the value of the issuerEvidenceMerchantPassedOnFundsInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getIssuerEvidenceMerchantPassedOnFundsInd() {
        return issuerEvidenceMerchantPassedOnFundsInd;
    }

    /**
     * Sets the value of the issuerEvidenceMerchantPassedOnFundsInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setIssuerEvidenceMerchantPassedOnFundsInd(YNType value) {
        this.issuerEvidenceMerchantPassedOnFundsInd = value;
    }

    /**
     * Gets the value of the prepaymentBalanceNotPaidInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getPrepaymentBalanceNotPaidInd() {
        return prepaymentBalanceNotPaidInd;
    }

    /**
     * Sets the value of the prepaymentBalanceNotPaidInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setPrepaymentBalanceNotPaidInd(YNType value) {
        this.prepaymentBalanceNotPaidInd = value;
    }

    /**
     * Gets the value of the providingPaymentProofOtherMeans property.
     * 
     * @return
     *     possible object is
     *     {@link ProvidingPaymentProofOtherType }
     *     
     */
    public ProvidingPaymentProofOtherType getProvidingPaymentProofOtherMeans() {
        return providingPaymentProofOtherMeans;
    }

    /**
     * Sets the value of the providingPaymentProofOtherMeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvidingPaymentProofOtherType }
     *     
     */
    public void setProvidingPaymentProofOtherMeans(ProvidingPaymentProofOtherType value) {
        this.providingPaymentProofOtherMeans = value;
    }

    /**
     * Gets the value of the processingErrorOtherExplanation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingErrorOtherExplanation() {
        return processingErrorOtherExplanation;
    }

    /**
     * Sets the value of the processingErrorOtherExplanation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingErrorOtherExplanation(String value) {
        this.processingErrorOtherExplanation = value;
    }

    /**
     * Gets the value of the incorrectCurrencyReason property.
     * 
     * @return
     *     possible object is
     *     {@link IncorrectCurrencyReasonType }
     *     
     */
    public IncorrectCurrencyReasonType getIncorrectCurrencyReason() {
        return incorrectCurrencyReason;
    }

    /**
     * Sets the value of the incorrectCurrencyReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncorrectCurrencyReasonType }
     *     
     */
    public void setIncorrectCurrencyReason(IncorrectCurrencyReasonType value) {
        this.incorrectCurrencyReason = value;
    }

    /**
     * Gets the value of the authorizationRequestDeclinedValidDataInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAuthorizationRequestDeclinedValidDataInd() {
        return authorizationRequestDeclinedValidDataInd;
    }

    /**
     * Sets the value of the authorizationRequestDeclinedValidDataInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuthorizationRequestDeclinedValidDataInd(Boolean value) {
        this.authorizationRequestDeclinedValidDataInd = value;
    }

    /**
     * Gets the value of the explainWhyValidDataInclusionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplainWhyValidDataInclusionReason() {
        return explainWhyValidDataInclusionReason;
    }

    /**
     * Sets the value of the explainWhyValidDataInclusionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplainWhyValidDataInclusionReason(String value) {
        this.explainWhyValidDataInclusionReason = value;
    }

    /**
     * Gets the value of the cardholderDidNotAgreeDCC property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getCardholderDidNotAgreeDCC() {
        return cardholderDidNotAgreeDCC;
    }

    /**
     * Sets the value of the cardholderDidNotAgreeDCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setCardholderDidNotAgreeDCC(YNType value) {
        this.cardholderDidNotAgreeDCC = value;
    }

    /**
     * Gets the value of the cardholderAttemptToResolve property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getCardholderAttemptToResolve() {
        return cardholderAttemptToResolve;
    }

    /**
     * Sets the value of the cardholderAttemptToResolve property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setCardholderAttemptToResolve(YNType value) {
        this.cardholderAttemptToResolve = value;
    }

    /**
     * Gets the value of the attemptToResolveProhLocalLaw property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getAttemptToResolveProhLocalLaw() {
        return attemptToResolveProhLocalLaw;
    }

    /**
     * Sets the value of the attemptToResolveProhLocalLaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setAttemptToResolveProhLocalLaw(YNType value) {
        this.attemptToResolveProhLocalLaw = value;
    }

    /**
     * Gets the value of the detailsOfLocalLaw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailsOfLocalLaw() {
        return detailsOfLocalLaw;
    }

    /**
     * Sets the value of the detailsOfLocalLaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailsOfLocalLaw(String value) {
        this.detailsOfLocalLaw = value;
    }

    /**
     * Gets the value of the otherTranInvolveDiffMerchantInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getOtherTranInvolveDiffMerchantInd() {
        return otherTranInvolveDiffMerchantInd;
    }

    /**
     * Sets the value of the otherTranInvolveDiffMerchantInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setOtherTranInvolveDiffMerchantInd(YNType value) {
        this.otherTranInvolveDiffMerchantInd = value;
    }

    /**
     * Gets the value of the otherTranSameMerchantInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getOtherTranSameMerchantInd() {
        return otherTranSameMerchantInd;
    }

    /**
     * Sets the value of the otherTranSameMerchantInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setOtherTranSameMerchantInd(YNType value) {
        this.otherTranSameMerchantInd = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the arn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARN() {
        return arn;
    }

    /**
     * Sets the value of the arn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARN(String value) {
        this.arn = value;
    }

}
