//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;


@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(Include.NON_EMPTY)
public class DisputeAuthorizationType {

    @JsonProperty("EFLDate")
    @JsonFormat(pattern = "yyyy-MM-dd  HH:mm:ss",
	shape = JsonFormat.Shape.STRING,
	locale = "pt-BR",
	timezone = "Brazil/East")
    protected Date eflDate;
    @JsonProperty("Region")
    protected List<String> region;
    @JsonProperty("ExplanationOfAuthorizationsPresented")
    protected String explanationOfAuthorizationsPresented;

    /**
     * Gets the value of the eflDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getEFLDate() {
        return eflDate;
    }

    /**
     * Sets the value of the eflDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEFLDate(Date value) {
        this.eflDate = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the region property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRegion() {
        if (region == null) {
            region = new ArrayList<String>();
        }
        return this.region;
    }

    /**
     * Gets the value of the explanationOfAuthorizationsPresented property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplanationOfAuthorizationsPresented() {
        return explanationOfAuthorizationsPresented;
    }

    /**
     * Sets the value of the explanationOfAuthorizationsPresented property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplanationOfAuthorizationsPresented(String value) {
        this.explanationOfAuthorizationsPresented = value;
    }

}
