//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisputeInvalidReasonDescType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DisputeInvalidReasonDescType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IDRA1"/>
 *     &lt;enumeration value="IDRA2"/>
 *     &lt;enumeration value="IDRA3"/>
 *     &lt;enumeration value="IDRA4"/>
 *     &lt;enumeration value="IDRA5"/>
 *     &lt;enumeration value="IDRA6"/>
 *     &lt;enumeration value="IDRA7"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DisputeInvalidReasonDescType")
@XmlEnum
public enum DisputeInvalidReasonDescType {

    @XmlEnumValue("IDRA1")
    IDRA_1("IDRA1"),
    @XmlEnumValue("IDRA2")
    IDRA_2("IDRA2"),
    @XmlEnumValue("IDRA3")
    IDRA_3("IDRA3"),
    @XmlEnumValue("IDRA4")
    IDRA_4("IDRA4"),
    @XmlEnumValue("IDRA5")
    IDRA_5("IDRA5"),
    @XmlEnumValue("IDRA6")
    IDRA_6("IDRA6"),
    @XmlEnumValue("IDRA7")
    IDRA_7("IDRA7");
    private final String value;

    DisputeInvalidReasonDescType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DisputeInvalidReasonDescType fromValue(String v) {
        for (DisputeInvalidReasonDescType c: DisputeInvalidReasonDescType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
