//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisputeFilingItemTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DisputeFilingItemTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Arbitration"/>
 *     &lt;enumeration value="Compliance"/>
 *     &lt;enumeration value="FilingResponse"/>
 *     &lt;enumeration value="AcknowledgementLetter"/>
 *     &lt;enumeration value="RejectionLetter"/>
 *     &lt;enumeration value="DecisionLetter"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DisputeFilingItemTypeType")
@XmlEnum
public enum DisputeFilingItemTypeType {

    @XmlEnumValue("Arbitration")
    ARBITRATION("Arbitration"),
    @XmlEnumValue("Compliance")
    COMPLIANCE("Compliance"),
    @XmlEnumValue("FilingResponse")
    FILING_RESPONSE("FilingResponse"),
    @XmlEnumValue("AcknowledgementLetter")
    ACKNOWLEDGEMENT_LETTER("AcknowledgementLetter"),
    @XmlEnumValue("RejectionLetter")
    REJECTION_LETTER("RejectionLetter"),
    @XmlEnumValue("DecisionLetter")
    DECISION_LETTER("DecisionLetter");
    private final String value;

    DisputeFilingItemTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DisputeFilingItemTypeType fromValue(String v) {
        for (DisputeFilingItemTypeType c: DisputeFilingItemTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
