//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import java.util.Date;

import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(Include.NON_EMPTY)
public class DisputeFinancialInformationType {

    @JsonProperty("VROLFinancialSentInd")
    protected Boolean vrolFinancialSentInd;
    @JsonProperty("VROLFinancialID")
    protected String vrolFinancialID;
    @JsonProperty("FinancialTransactionType")
    protected String financialTransactionType;
    @JsonProperty("FinancialAmt")
    protected AmountType financialAmt;
    @JsonProperty("DisputeCategory")
    protected DisputeCategoryType disputeCategory;
    @JsonProperty("DisputeCondition")
    protected String disputeCondition;
    @JsonProperty("DisputeId")
    protected Long disputeId;
    @JsonProperty("VROLBundleCaseNumber")
    protected Long vrolBundleCaseNumber;
    @JsonProperty("TransactionID")
    protected String transactionID;
    @JsonProperty("IssuerCaseNumber")
    protected String issuerCaseNumber;
    @JsonProperty("AcquirerCaseNumber")
    protected String acquirerCaseNumber;
    @JsonProperty("OpposerExpectedRespDate")
    @JsonFormat(pattern = "yyyy-MM-dd  HH:mm:ss",
	shape = JsonFormat.Shape.STRING,
	locale = "pt-BR",
	timezone = "Brazil/East")
    protected Date opposerExpectedRespDate;

    /**
     * Gets the value of the vrolFinancialSentInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVROLFinancialSentInd() {
        return vrolFinancialSentInd;
    }

    /**
     * Sets the value of the vrolFinancialSentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVROLFinancialSentInd(Boolean value) {
        this.vrolFinancialSentInd = value;
    }

    /**
     * Gets the value of the vrolFinancialID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVROLFinancialID() {
        return vrolFinancialID;
    }

    /**
     * Sets the value of the vrolFinancialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVROLFinancialID(String value) {
        this.vrolFinancialID = value;
    }

    /**
     * Gets the value of the financialTransactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialTransactionType() {
        return financialTransactionType;
    }

    /**
     * Sets the value of the financialTransactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialTransactionType(String value) {
        this.financialTransactionType = value;
    }

    /**
     * Gets the value of the financialAmt property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getFinancialAmt() {
        return financialAmt;
    }

    /**
     * Sets the value of the financialAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setFinancialAmt(AmountType value) {
        this.financialAmt = value;
    }

    /**
     * Gets the value of the disputeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeCategoryType }
     *     
     */
    public DisputeCategoryType getDisputeCategory() {
        return disputeCategory;
    }

    /**
     * Sets the value of the disputeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeCategoryType }
     *     
     */
    public void setDisputeCategory(DisputeCategoryType value) {
        this.disputeCategory = value;
    }

    /**
     * Gets the value of the disputeCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeCondition() {
        return disputeCondition;
    }

    /**
     * Sets the value of the disputeCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeCondition(String value) {
        this.disputeCondition = value;
    }

    /**
     * Gets the value of the disputeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDisputeId() {
        return disputeId;
    }

    /**
     * Sets the value of the disputeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDisputeId(Long value) {
        this.disputeId = value;
    }

    /**
     * Gets the value of the vrolBundleCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVROLBundleCaseNumber() {
        return vrolBundleCaseNumber;
    }

    /**
     * Sets the value of the vrolBundleCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVROLBundleCaseNumber(Long value) {
        this.vrolBundleCaseNumber = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the issuerCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerCaseNumber() {
        return issuerCaseNumber;
    }

    /**
     * Sets the value of the issuerCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerCaseNumber(String value) {
        this.issuerCaseNumber = value;
    }

    /**
     * Gets the value of the acquirerCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquirerCaseNumber() {
        return acquirerCaseNumber;
    }

    /**
     * Sets the value of the acquirerCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquirerCaseNumber(String value) {
        this.acquirerCaseNumber = value;
    }

    /**
     * Gets the value of the opposerExpectedRespDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getOpposerExpectedRespDate() {
        return opposerExpectedRespDate;
    }

    /**
     * Sets the value of the opposerExpectedRespDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOpposerExpectedRespDate(Date value) {
        this.opposerExpectedRespDate = value;
    }

}
