//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EFLIndType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EFLIndType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Exist"/>
 *     &lt;enumeration value="NotExist"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EFLIndType")
@XmlEnum
public enum EFLIndType {

    @XmlEnumValue("Exist")
    EXIST("Exist"),
    @XmlEnumValue("NotExist")
    NOT_EXIST("NotExist"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    EFLIndType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EFLIndType fromValue(String v) {
        for (EFLIndType c: EFLIndType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
