//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExceptionRequestBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExceptionRequestBodyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}RequestBodyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="SubmitExceptionRequest" type="{http://www.visa.com/ROLSI}RTSISubmitExceptionType"/>
 *           &lt;element name="InquiryExceptionRequest" type="{http://www.visa.com/ROLSI}RTSIInquiryExceptionFileExceptionType"/>
 *           &lt;element name="ExceptionDetailsRequest" type="{http://www.visa.com/ROLSI}RTSIExceptionDetailsRequestType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExceptionRequestBodyType", propOrder = {
    "submitExceptionRequest",
    "inquiryExceptionRequest",
    "exceptionDetailsRequest"
})
public class ExceptionRequestBodyType
    extends RequestBodyType
{

    @XmlElement(name = "SubmitExceptionRequest")
    protected RTSISubmitExceptionType submitExceptionRequest;
    @XmlElement(name = "InquiryExceptionRequest")
    protected RTSIInquiryExceptionFileExceptionType inquiryExceptionRequest;
    @XmlElement(name = "ExceptionDetailsRequest")
    protected RTSIExceptionDetailsRequestType exceptionDetailsRequest;

    /**
     * Gets the value of the submitExceptionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RTSISubmitExceptionType }
     *     
     */
    public RTSISubmitExceptionType getSubmitExceptionRequest() {
        return submitExceptionRequest;
    }

    /**
     * Sets the value of the submitExceptionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSISubmitExceptionType }
     *     
     */
    public void setSubmitExceptionRequest(RTSISubmitExceptionType value) {
        this.submitExceptionRequest = value;
    }

    /**
     * Gets the value of the inquiryExceptionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIInquiryExceptionFileExceptionType }
     *     
     */
    public RTSIInquiryExceptionFileExceptionType getInquiryExceptionRequest() {
        return inquiryExceptionRequest;
    }

    /**
     * Sets the value of the inquiryExceptionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIInquiryExceptionFileExceptionType }
     *     
     */
    public void setInquiryExceptionRequest(RTSIInquiryExceptionFileExceptionType value) {
        this.inquiryExceptionRequest = value;
    }

    /**
     * Gets the value of the exceptionDetailsRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIExceptionDetailsRequestType }
     *     
     */
    public RTSIExceptionDetailsRequestType getExceptionDetailsRequest() {
        return exceptionDetailsRequest;
    }

    /**
     * Sets the value of the exceptionDetailsRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIExceptionDetailsRequestType }
     *     
     */
    public void setExceptionDetailsRequest(RTSIExceptionDetailsRequestType value) {
        this.exceptionDetailsRequest = value;
    }

}
