//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilingRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilingRespType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}CommonFormDataType">
 *       &lt;sequence>
 *         &lt;element name="CaseFilingResponse" type="{http://www.visa.com/ROLSI}CaseFilingResponseDescType" minOccurs="0"/>
 *         &lt;element name="RequestToWithdrawInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.visa.com/ROLSI}FilingRespTypeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilingRespType", propOrder = {
    "caseFilingResponse",
    "requestToWithdrawInd"
})
public class FilingRespType
    extends CommonFormDataType
{

    @XmlElement(name = "CaseFilingResponse")
    protected String caseFilingResponse;
    @XmlElement(name = "RequestToWithdrawInd")
    protected Boolean requestToWithdrawInd;
    @XmlAttribute(name = "type")
    protected FilingRespTypeType type;

    /**
     * Gets the value of the caseFilingResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseFilingResponse() {
        return caseFilingResponse;
    }

    /**
     * Sets the value of the caseFilingResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseFilingResponse(String value) {
        this.caseFilingResponse = value;
    }

    /**
     * Gets the value of the requestToWithdrawInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestToWithdrawInd() {
        return requestToWithdrawInd;
    }

    /**
     * Sets the value of the requestToWithdrawInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestToWithdrawInd(Boolean value) {
        this.requestToWithdrawInd = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FilingRespTypeType }
     *     
     */
    public FilingRespTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilingRespTypeType }
     *     
     */
    public void setType(FilingRespTypeType value) {
        this.type = value;
    }

}
