//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinIdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FinId" type="{http://www.visa.com/ROLSI}FinIdType" minOccurs="0"/>
 *         &lt;element name="FinType" type="{http://www.visa.com/ROLSI}FnRespType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinIdentifierType", propOrder = {
    "finId",
    "finType"
})
public class FinIdentifierType {

    @XmlElement(name = "FinId")
    protected FinIdType finId;
    @XmlElement(name = "FinType")
    protected String finType;

    /**
     * Gets the value of the finId property.
     * 
     * @return
     *     possible object is
     *     {@link FinIdType }
     *     
     */
    public FinIdType getFinId() {
        return finId;
    }

    /**
     * Sets the value of the finId property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinIdType }
     *     
     */
    public void setFinId(FinIdType value) {
        this.finId = value;
    }

    /**
     * Gets the value of the finType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinType() {
        return finType;
    }

    /**
     * Sets the value of the finType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinType(String value) {
        this.finType = value;
    }

}
