//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FnType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FnType">
 *   &lt;restriction base="{http://www.visa.com/ROLSI}QnType">
 *     &lt;enumeration value="ChargebackFinancial"/>
 *     &lt;enumeration value="RepresentmentFinancial"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FnType")
@XmlEnum(QnType.class)
public enum FnType {

    @XmlEnumValue("ChargebackFinancial")
    CHARGEBACK_FINANCIAL(QnType.CHARGEBACK_FINANCIAL),
    @XmlEnumValue("RepresentmentFinancial")
    REPRESENTMENT_FINANCIAL(QnType.REPRESENTMENT_FINANCIAL);
    private final QnType value;

    FnType(QnType v) {
        value = v;
    }

    public QnType value() {
        return value;
    }

    public static FnType fromValue(QnType v) {
        for (FnType c: FnType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
