//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FormatKQueueItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormatKQueueItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.visa.com/ROLSI}BatchQueueItemSID" minOccurs="0"/>
 *         &lt;element name="QuickFormID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Action" type="{http://www.visa.com/ROLSI}DisputeKQueueActionType" minOccurs="0"/>
 *         &lt;element name="Source" type="{http://www.visa.com/ROLSI}DisputeKSourceType" minOccurs="0"/>
 *         &lt;element name="RequestDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}AccountNumber" minOccurs="0"/>
 *         &lt;element name="Amount" type="{http://www.visa.com/ROLSI}AmountType" minOccurs="0"/>
 *         &lt;element name="DaysAged" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ARN" minOccurs="0"/>
 *         &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}TransactionID" minOccurs="0"/>
 *         &lt;element name="ErrorCondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormatKQueueItemType", propOrder = {
    "batchQueueItemSID",
    "quickFormID",
    "action",
    "source",
    "requestDate",
    "accountNumber",
    "amount",
    "daysAged",
    "arn",
    "user",
    "transactionID",
    "errorCondition"
})
public class FormatKQueueItemType {

    @XmlElement(name = "BatchQueueItemSID")
    protected Long batchQueueItemSID;
    @XmlElement(name = "QuickFormID")
    protected Long quickFormID;
    @XmlElement(name = "Action")
    @XmlSchemaType(name = "string")
    protected DisputeKQueueActionType action;
    @XmlElement(name = "Source")
    @XmlSchemaType(name = "string")
    protected DisputeKSourceType source;
    @XmlElement(name = "RequestDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar requestDate;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "Amount")
    protected AmountType amount;
    @XmlElement(name = "DaysAged")
    protected BigInteger daysAged;
    @XmlElement(name = "ARN")
    protected String arn;
    @XmlElement(name = "User")
    protected String user;
    @XmlElement(name = "TransactionID")
    protected String transactionID;
    @XmlElement(name = "ErrorCondition")
    protected String errorCondition;

    /**
     * Gets the value of the batchQueueItemSID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBatchQueueItemSID() {
        return batchQueueItemSID;
    }

    /**
     * Sets the value of the batchQueueItemSID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBatchQueueItemSID(Long value) {
        this.batchQueueItemSID = value;
    }

    /**
     * Gets the value of the quickFormID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuickFormID() {
        return quickFormID;
    }

    /**
     * Sets the value of the quickFormID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuickFormID(Long value) {
        this.quickFormID = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeKQueueActionType }
     *     
     */
    public DisputeKQueueActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeKQueueActionType }
     *     
     */
    public void setAction(DisputeKQueueActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeKSourceType }
     *     
     */
    public DisputeKSourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeKSourceType }
     *     
     */
    public void setSource(DisputeKSourceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the requestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestDate() {
        return requestDate;
    }

    /**
     * Sets the value of the requestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestDate(XMLGregorianCalendar value) {
        this.requestDate = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the daysAged property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDaysAged() {
        return daysAged;
    }

    /**
     * Sets the value of the daysAged property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDaysAged(BigInteger value) {
        this.daysAged = value;
    }

    /**
     * Gets the value of the arn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARN() {
        return arn;
    }

    /**
     * Sets the value of the arn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARN(String value) {
        this.arn = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the errorCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCondition() {
        return errorCondition;
    }

    /**
     * Sets the value of the errorCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCondition(String value) {
        this.errorCondition = value;
    }

}
