//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FraudReportResponseBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FraudReportResponseBodyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}ResponseBodyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="SubmitFraudReportResponse" type="{http://www.visa.com/ROLSI}SubmitFraudReportResponseType"/>
 *           &lt;element name="FraudReportDetailsResponse" type="{http://www.visa.com/ROLSI}RTSIFraudReportDetailsResposneType"/>
 *           &lt;element name="SubmitIgnoreResponse" type="{http://www.visa.com/ROLSI}SubmitIgnoreResponseType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FraudReportResponseBodyType", propOrder = {
    "submitFraudReportResponse",
    "fraudReportDetailsResponse",
    "submitIgnoreResponse"
})
public class FraudReportResponseBodyType
    extends ResponseBodyType
{

    @XmlElement(name = "SubmitFraudReportResponse")
    protected SubmitFraudReportResponseType submitFraudReportResponse;
    @XmlElement(name = "FraudReportDetailsResponse")
    protected RTSIFraudReportDetailsResposneType fraudReportDetailsResponse;
    @XmlElement(name = "SubmitIgnoreResponse")
    protected SubmitIgnoreResponseType submitIgnoreResponse;

    /**
     * Gets the value of the submitFraudReportResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitFraudReportResponseType }
     *     
     */
    public SubmitFraudReportResponseType getSubmitFraudReportResponse() {
        return submitFraudReportResponse;
    }

    /**
     * Sets the value of the submitFraudReportResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitFraudReportResponseType }
     *     
     */
    public void setSubmitFraudReportResponse(SubmitFraudReportResponseType value) {
        this.submitFraudReportResponse = value;
    }

    /**
     * Gets the value of the fraudReportDetailsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIFraudReportDetailsResposneType }
     *     
     */
    public RTSIFraudReportDetailsResposneType getFraudReportDetailsResponse() {
        return fraudReportDetailsResponse;
    }

    /**
     * Sets the value of the fraudReportDetailsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIFraudReportDetailsResposneType }
     *     
     */
    public void setFraudReportDetailsResponse(RTSIFraudReportDetailsResposneType value) {
        this.fraudReportDetailsResponse = value;
    }

    /**
     * Gets the value of the submitIgnoreResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitIgnoreResponseType }
     *     
     */
    public SubmitIgnoreResponseType getSubmitIgnoreResponse() {
        return submitIgnoreResponse;
    }

    /**
     * Sets the value of the submitIgnoreResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitIgnoreResponseType }
     *     
     */
    public void setSubmitIgnoreResponse(SubmitIgnoreResponseType value) {
        this.submitIgnoreResponse = value;
    }

}
