//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCaseDetailsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetCaseDetailsResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CaseInformation" type="{http://www.visa.com/ROLSI}CaseInfoDataType" minOccurs="0"/>
 *         &lt;element name="TransactionInformation" type="{http://www.visa.com/ROLSI}TransactionInformationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCaseDetailsResponseType", propOrder = {
    "caseInformation",
    "transactionInformation"
})
public class GetCaseDetailsResponseType {

    @XmlElement(name = "CaseInformation")
    protected CaseInfoDataType caseInformation;
    @XmlElement(name = "TransactionInformation")
    protected TransactionInformationType transactionInformation;

    /**
     * Gets the value of the caseInformation property.
     * 
     * @return
     *     possible object is
     *     {@link CaseInfoDataType }
     *     
     */
    public CaseInfoDataType getCaseInformation() {
        return caseInformation;
    }

    /**
     * Sets the value of the caseInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseInfoDataType }
     *     
     */
    public void setCaseInformation(CaseInfoDataType value) {
        this.caseInformation = value;
    }

    /**
     * Gets the value of the transactionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionInformationType }
     *     
     */
    public TransactionInformationType getTransactionInformation() {
        return transactionInformation;
    }

    /**
     * Sets the value of the transactionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionInformationType }
     *     
     */
    public void setTransactionInformation(TransactionInformationType value) {
        this.transactionInformation = value;
    }

}
