//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetGMFPDetailsRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetGMFPDetailsRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}RequestBodyType">
 *       &lt;sequence>
 *         &lt;element name="GetGMFPDetailsRequest" type="{http://www.visa.com/ROLSI}GetGMFPDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetGMFPDetailsRequestType", propOrder = {
    "getGMFPDetailsRequest"
})
public class GetGMFPDetailsRequestType
    extends RequestBodyType
{

    @XmlElement(name = "GetGMFPDetailsRequest", required = true)
    protected GetGMFPDetailsType getGMFPDetailsRequest;

    /**
     * Gets the value of the getGMFPDetailsRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetGMFPDetailsType }
     *     
     */
    public GetGMFPDetailsType getGetGMFPDetailsRequest() {
        return getGMFPDetailsRequest;
    }

    /**
     * Sets the value of the getGMFPDetailsRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetGMFPDetailsType }
     *     
     */
    public void setGetGMFPDetailsRequest(GetGMFPDetailsType value) {
        this.getGMFPDetailsRequest = value;
    }

}
