//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LetterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LetterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.visa.com/ROLSI}FilingId" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}LetterId" minOccurs="0"/>
 *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Jurisdiction" type="{http://www.visa.com/ROLSI}JurisdictionEnum" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}AppealInd" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.visa.com/ROLSI}LetterTypeEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LetterType", propOrder = {
    "filingId",
    "letterId",
    "text",
    "jurisdiction",
    "appealInd"
})
public class LetterType {

    @XmlElement(name = "FilingId")
    protected Long filingId;
    @XmlElement(name = "LetterId")
    protected Long letterId;
    @XmlElement(name = "Text", required = true)
    protected String text;
    @XmlElement(name = "Jurisdiction")
    @XmlSchemaType(name = "string")
    protected JurisdictionEnum jurisdiction;
    @XmlElement(name = "AppealInd")
    protected Boolean appealInd;
    @XmlAttribute(name = "type")
    protected LetterTypeEnum type;

    /**
     * Used in RTSI and IECF only
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFilingId() {
        return filingId;
    }

    /**
     * Sets the value of the filingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFilingId(Long value) {
        this.filingId = value;
    }

    /**
     * Used in RTSI and IECF only
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLetterId() {
        return letterId;
    }

    /**
     * Sets the value of the letterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLetterId(Long value) {
        this.letterId = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the jurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link JurisdictionEnum }
     *     
     */
    public JurisdictionEnum getJurisdiction() {
        return jurisdiction;
    }

    /**
     * Sets the value of the jurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JurisdictionEnum }
     *     
     */
    public void setJurisdiction(JurisdictionEnum value) {
        this.jurisdiction = value;
    }

    /**
     * Gets the value of the appealInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAppealInd() {
        return appealInd;
    }

    /**
     * Sets the value of the appealInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAppealInd(Boolean value) {
        this.appealInd = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LetterTypeEnum }
     *     
     */
    public LetterTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LetterTypeEnum }
     *     
     */
    public void setType(LetterTypeEnum value) {
        this.type = value;
    }

}
