//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LetterTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LetterTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Acknowledgement"/>
 *     &lt;enumeration value="Rejection"/>
 *     &lt;enumeration value="Final Decision"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LetterTypeEnum")
@XmlEnum
public enum LetterTypeEnum {

    @XmlEnumValue("Acknowledgement")
    ACKNOWLEDGEMENT("Acknowledgement"),
    @XmlEnumValue("Rejection")
    REJECTION("Rejection"),
    @XmlEnumValue("Final Decision")
    FINAL_DECISION("Final Decision");
    private final String value;

    LetterTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LetterTypeEnum fromValue(String v) {
        for (LetterTypeEnum c: LetterTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
