//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ManualCaseCreationResponseBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManualCaseCreationResponseBodyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}ResponseBodyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="ManualCaseCreationResponse" type="{http://www.visa.com/ROLSI}RTSIManualCaseCreationResponseType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManualCaseCreationResponseBodyType", propOrder = {
    "manualCaseCreationResponse"
})
public class ManualCaseCreationResponseBodyType
    extends ResponseBodyType
{

    @XmlElement(name = "ManualCaseCreationResponse")
    protected RTSIManualCaseCreationResponseType manualCaseCreationResponse;

    /**
     * Gets the value of the manualCaseCreationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIManualCaseCreationResponseType }
     *     
     */
    public RTSIManualCaseCreationResponseType getManualCaseCreationResponse() {
        return manualCaseCreationResponse;
    }

    /**
     * Sets the value of the manualCaseCreationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIManualCaseCreationResponseType }
     *     
     */
    public void setManualCaseCreationResponse(RTSIManualCaseCreationResponseType value) {
        this.manualCaseCreationResponse = value;
    }

}
