//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageIndicatorsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageIndicatorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActiveMessageID" type="{http://www.visa.com/ROLSI}ActiveMessageIDType" minOccurs="0"/>
 *         &lt;element name="MessageType" type="{http://www.visa.com/ROLSI}MessageSimpleType" minOccurs="0"/>
 *         &lt;element name="MessageIndicatorType" type="{http://www.visa.com/ROLSI}MsgType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageIndicatorsType", propOrder = {
    "activeMessageID",
    "messageType",
    "messageIndicatorType"
})
public class MessageIndicatorsType {

    @XmlElement(name = "ActiveMessageID")
    protected ActiveMessageIDType activeMessageID;
    @XmlElement(name = "MessageType")
    @XmlSchemaType(name = "string")
    protected MessageSimpleType messageType;
    @XmlElement(name = "MessageIndicatorType")
    @XmlSchemaType(name = "string")
    protected MsgType messageIndicatorType;

    /**
     * Gets the value of the activeMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveMessageIDType }
     *     
     */
    public ActiveMessageIDType getActiveMessageID() {
        return activeMessageID;
    }

    /**
     * Sets the value of the activeMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveMessageIDType }
     *     
     */
    public void setActiveMessageID(ActiveMessageIDType value) {
        this.activeMessageID = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link MessageSimpleType }
     *     
     */
    public MessageSimpleType getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageSimpleType }
     *     
     */
    public void setMessageType(MessageSimpleType value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the messageIndicatorType property.
     * 
     * @return
     *     possible object is
     *     {@link MsgType }
     *     
     */
    public MsgType getMessageIndicatorType() {
        return messageIndicatorType;
    }

    /**
     * Sets the value of the messageIndicatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgType }
     *     
     */
    public void setMessageIndicatorType(MsgType value) {
        this.messageIndicatorType = value;
    }

}
