//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MiscFeeResponseBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MiscFeeResponseBodyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}ResponseBodyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="MiscFeeEntryResponse" type="{http://www.visa.com/ROLSI}MiscFeeEntryResponseType"/>
 *           &lt;element name="MiscFeeDetailsResponse" type="{http://www.visa.com/ROLSI}MiscFeeDetailsResponseType"/>
 *           &lt;element name="MiscFeeSwitchStatusResponse" type="{http://www.visa.com/ROLSI}MiscFeeSwitchStatusResponseType"/>
 *           &lt;element name="CloseMiscFeeResponse" type="{http://www.visa.com/ROLSI}CloseMiscFeeResponseType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MiscFeeResponseBodyType", propOrder = {
    "miscFeeEntryResponse",
    "miscFeeDetailsResponse",
    "miscFeeSwitchStatusResponse",
    "closeMiscFeeResponse"
})
public class MiscFeeResponseBodyType
    extends ResponseBodyType
{

    @XmlElement(name = "MiscFeeEntryResponse")
    protected MiscFeeEntryResponseType miscFeeEntryResponse;
    @XmlElement(name = "MiscFeeDetailsResponse")
    protected MiscFeeDetailsResponseType miscFeeDetailsResponse;
    @XmlElement(name = "MiscFeeSwitchStatusResponse")
    protected MiscFeeSwitchStatusResponseType miscFeeSwitchStatusResponse;
    @XmlElement(name = "CloseMiscFeeResponse")
    protected CloseMiscFeeResponseType closeMiscFeeResponse;

    /**
     * Gets the value of the miscFeeEntryResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MiscFeeEntryResponseType }
     *     
     */
    public MiscFeeEntryResponseType getMiscFeeEntryResponse() {
        return miscFeeEntryResponse;
    }

    /**
     * Sets the value of the miscFeeEntryResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscFeeEntryResponseType }
     *     
     */
    public void setMiscFeeEntryResponse(MiscFeeEntryResponseType value) {
        this.miscFeeEntryResponse = value;
    }

    /**
     * Gets the value of the miscFeeDetailsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MiscFeeDetailsResponseType }
     *     
     */
    public MiscFeeDetailsResponseType getMiscFeeDetailsResponse() {
        return miscFeeDetailsResponse;
    }

    /**
     * Sets the value of the miscFeeDetailsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscFeeDetailsResponseType }
     *     
     */
    public void setMiscFeeDetailsResponse(MiscFeeDetailsResponseType value) {
        this.miscFeeDetailsResponse = value;
    }

    /**
     * Gets the value of the miscFeeSwitchStatusResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MiscFeeSwitchStatusResponseType }
     *     
     */
    public MiscFeeSwitchStatusResponseType getMiscFeeSwitchStatusResponse() {
        return miscFeeSwitchStatusResponse;
    }

    /**
     * Sets the value of the miscFeeSwitchStatusResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscFeeSwitchStatusResponseType }
     *     
     */
    public void setMiscFeeSwitchStatusResponse(MiscFeeSwitchStatusResponseType value) {
        this.miscFeeSwitchStatusResponse = value;
    }

    /**
     * Gets the value of the closeMiscFeeResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CloseMiscFeeResponseType }
     *     
     */
    public CloseMiscFeeResponseType getCloseMiscFeeResponse() {
        return closeMiscFeeResponse;
    }

    /**
     * Sets the value of the closeMiscFeeResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloseMiscFeeResponseType }
     *     
     */
    public void setCloseMiscFeeResponse(CloseMiscFeeResponseType value) {
        this.closeMiscFeeResponse = value;
    }

}
