//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * @definition: More Information.
 * 
 * <p>Java class for MoreInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MoreInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConditionOfGoods" type="{http://www.visa.com/ROLSI}ConditionOfGoodsType" minOccurs="0"/>
 *         &lt;element name="VersionOfItems" type="{http://www.visa.com/ROLSI}VersionOfItemsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MoreInfoType", propOrder = {
    "conditionOfGoods",
    "versionOfItems"
})
public class MoreInfoType {

    @XmlElement(name = "ConditionOfGoods")
    protected String conditionOfGoods;
    @XmlElement(name = "VersionOfItems")
    protected String versionOfItems;

    /**
     * Gets the value of the conditionOfGoods property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionOfGoods() {
        return conditionOfGoods;
    }

    /**
     * Sets the value of the conditionOfGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionOfGoods(String value) {
        this.conditionOfGoods = value;
    }

    /**
     * Gets the value of the versionOfItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionOfItems() {
        return versionOfItems;
    }

    /**
     * Sets the value of the versionOfItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionOfItems(String value) {
        this.versionOfItems = value;
    }

}
