//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonFinancialMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NonFinancialMessageType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}AbstractMessageType">
 *       &lt;sequence>
 *         &lt;element name="MessageType" type="{http://www.visa.com/ROLSI}MessageSimpleType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonFinancialMessageType", propOrder = {
    "messageType"
})
public class NonFinancialMessageType
    extends AbstractMessageType
{

    @XmlElement(name = "MessageType", required = true)
    @XmlSchemaType(name = "string")
    protected MessageSimpleType messageType;

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link MessageSimpleType }
     *     
     */
    public MessageSimpleType getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageSimpleType }
     *     
     */
    public void setMessageType(MessageSimpleType value) {
        this.messageType = value;
    }

}
