//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuickFormActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QuickFormActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Pend"/>
 *     &lt;enumeration value="Submit"/>
 *     &lt;enumeration value="SubmitForReview"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QuickFormActionType")
@XmlEnum
public enum QuickFormActionType {

    @XmlEnumValue("Pend")
    PEND("Pend"),
    @XmlEnumValue("Submit")
    SUBMIT("Submit"),
    @XmlEnumValue("SubmitForReview")
    SUBMIT_FOR_REVIEW("SubmitForReview");
    private final String value;

    QuickFormActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QuickFormActionType fromValue(String v) {
        for (QuickFormActionType c: QuickFormActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
