//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RequestNameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LoginRequest"/>
 *     &lt;enumeration value="LoginSubmitRequest"/>
 *     &lt;enumeration value="ChangePasswordRequest"/>
 *     &lt;enumeration value="ChangePasswordSubmitRequest"/>
 *     &lt;enumeration value="TestAuthenticationRequest"/>
 *     &lt;enumeration value="LogoutRequest"/>
 *     &lt;enumeration value="InitiateDisputeRequest"/>
 *     &lt;enumeration value="InitiateDisputeFromRfiRequest"/>
 *     &lt;enumeration value="ContinueDisputeRequest"/>
 *     &lt;enumeration value="QuestionnaireAttachmentRequest"/>
 *     &lt;enumeration value="SubmitRFIRequest"/>
 *     &lt;enumeration value="GetRFITranDetailRequest"/>
 *     &lt;enumeration value="GetRFITransactionsRequest"/>
 *     &lt;enumeration value="HyperSearchRequest"/>
 *     &lt;enumeration value="SubmitRFCFulfillmentRequest"/>
 *     &lt;enumeration value="SubmitRFCNonFulfillmentRequest"/>
 *     &lt;enumeration value="SubmitRFCRequest"/>
 *     &lt;enumeration value="SubmitIgnoreRequest"/>
 *     &lt;enumeration value="CloseRFCRequest"/>
 *     &lt;enumeration value="GetRFCDetailRequest"/>
 *     &lt;enumeration value="GetRFCFulfillmentRequest"/>
 *     &lt;enumeration value="GetRFCNonFulfillmentRequest"/>
 *     &lt;enumeration value="GetRFCAdviceRequest"/>
 *     &lt;enumeration value="GetMyQueueRequest"/>
 *     &lt;enumeration value="SubmitFinancialReversalRequest"/>
 *     &lt;enumeration value="GetFinancialDetailRequest"/>
 *     &lt;enumeration value="SubmitFraudReportRequest"/>
 *     &lt;enumeration value="FraudReportDetailsRequest"/>
 *     &lt;enumeration value="SubmitFraudIgnoreRequest"/>
 *     &lt;enumeration value="SubmitExceptionRequest"/>
 *     &lt;enumeration value="InquiryExceptionRequest"/>
 *     &lt;enumeration value="ExceptionDetailsRequest"/>
 *     &lt;enumeration value="DisputeQuestionnaireRequest"/>
 *     &lt;enumeration value="UploadImageRequest"/>
 *     &lt;enumeration value="GetQuestionnaireDataRequest"/>
 *     &lt;enumeration value="GetImageRequest"/>
 *     &lt;enumeration value="StopPaymentInquiryRequest"/>
 *     &lt;enumeration value="StopPaymentOrderRequest"/>
 *     &lt;enumeration value="StopPaymentDetailsRequest"/>
 *     &lt;enumeration value="AccountingEntryRequest"/>
 *     &lt;enumeration value="AccountingEntryDetailsRequest"/>
 *     &lt;enumeration value="MiscFeeEntryRequest"/>
 *     &lt;enumeration value="MiscFeeDetailsRequest"/>
 *     &lt;enumeration value="SubmitAdjustmentRequest"/>
 *     &lt;enumeration value="AdjustmentDetailsRequest"/>
 *     &lt;enumeration value="ManualCaseCreationRequest"/>
 *     &lt;enumeration value="SubmitTranInquiryRequest"/>
 *     &lt;enumeration value="GetTransInquiryResultsRequest"/>
 *     &lt;enumeration value="GetTransDetailsRequest"/>
 *     &lt;enumeration value="CreateCaseFromTransactionRequest"/>
 *     &lt;enumeration value="SetTransactionForCaseRequest"/>
 *     &lt;enumeration value="LinkUnlinkCasesRequest"/>
 *     &lt;enumeration value="IgnoreRejectRequest"/>
 *     &lt;enumeration value="GetMMIRequest"/>
 *     &lt;enumeration value="GetTransactionsFromCaseRequest"/>
 *     &lt;enumeration value="GetEventTrackingVelocityTagsRequest"/>
 *     &lt;enumeration value="SubmitQuickFormRequest"/>
 *     &lt;enumeration value="GetVDASDetailsRequest"/>
 *     &lt;enumeration value="IgnoreVDASRequest"/>
 *     &lt;enumeration value="IgnoreReverseVDASRequest"/>
 *     &lt;enumeration value="ViewPotentialQnMatchesRequest"/>
 *     &lt;enumeration value="ViewPotentialVDASMatchesRequest"/>
 *     &lt;enumeration value="CloseMiscFeeRequest"/>
 *     &lt;enumeration value="CloseMessageRequest"/>
 *     &lt;enumeration value="RetrievePotentialMatchesRequest"/>
 *     &lt;enumeration value="IgnoreUnmatchedItemRequest"/>
 *     &lt;enumeration value="AddUnmatchedItemToCaseRequest"/>
 *     &lt;enumeration value="LinkAsSameDisputeRequest"/>
 *     &lt;enumeration value="BatchQueueRequest"/>
 *     &lt;enumeration value="MarkBatchQueueItemAsReadRequest"/>
 *     &lt;enumeration value="ConfirmFraudReportRequest"/>
 *     &lt;enumeration value="GetGMFPDetailsRequest"/>
 *     &lt;enumeration value="UpdateGMFPStatusRequest"/>
 *     &lt;enumeration value="CreateMessageRequest"/>
 *     &lt;enumeration value="UploadMessageImageRequest"/>
 *     &lt;enumeration value="GetMessageRequest"/>
 *     &lt;enumeration value="GetMessageImageRequest"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RequestNameType")
@XmlEnum
public enum RequestNameType {

    @XmlEnumValue("LoginRequest")
    LOGIN_REQUEST("LoginRequest"),
    @XmlEnumValue("LoginSubmitRequest")
    LOGIN_SUBMIT_REQUEST("LoginSubmitRequest"),
    @XmlEnumValue("ChangePasswordRequest")
    CHANGE_PASSWORD_REQUEST("ChangePasswordRequest"),
    @XmlEnumValue("ChangePasswordSubmitRequest")
    CHANGE_PASSWORD_SUBMIT_REQUEST("ChangePasswordSubmitRequest"),
    @XmlEnumValue("TestAuthenticationRequest")
    TEST_AUTHENTICATION_REQUEST("TestAuthenticationRequest"),
    @XmlEnumValue("LogoutRequest")
    LOGOUT_REQUEST("LogoutRequest"),
    @XmlEnumValue("InitiateDisputeRequest")
    INITIATE_DISPUTE_REQUEST("InitiateDisputeRequest"),
    @XmlEnumValue("InitiateDisputeFromRfiRequest")
    INITIATE_DISPUTE_FROM_RFI_REQUEST("InitiateDisputeFromRfiRequest"),
    @XmlEnumValue("ContinueDisputeRequest")
    CONTINUE_DISPUTE_REQUEST("ContinueDisputeRequest"),
    @XmlEnumValue("QuestionnaireAttachmentRequest")
    QUESTIONNAIRE_ATTACHMENT_REQUEST("QuestionnaireAttachmentRequest"),
    @XmlEnumValue("SubmitRFIRequest")
    SUBMIT_RFI_REQUEST("SubmitRFIRequest"),
    @XmlEnumValue("GetRFITranDetailRequest")
    GET_RFI_TRAN_DETAIL_REQUEST("GetRFITranDetailRequest"),
    @XmlEnumValue("GetRFITransactionsRequest")
    GET_RFI_TRANSACTIONS_REQUEST("GetRFITransactionsRequest"),
    @XmlEnumValue("HyperSearchRequest")
    HYPER_SEARCH_REQUEST("HyperSearchRequest"),
    @XmlEnumValue("SubmitRFCFulfillmentRequest")
    SUBMIT_RFC_FULFILLMENT_REQUEST("SubmitRFCFulfillmentRequest"),
    @XmlEnumValue("SubmitRFCNonFulfillmentRequest")
    SUBMIT_RFC_NON_FULFILLMENT_REQUEST("SubmitRFCNonFulfillmentRequest"),
    @XmlEnumValue("SubmitRFCRequest")
    SUBMIT_RFC_REQUEST("SubmitRFCRequest"),
    @XmlEnumValue("SubmitIgnoreRequest")
    SUBMIT_IGNORE_REQUEST("SubmitIgnoreRequest"),
    @XmlEnumValue("CloseRFCRequest")
    CLOSE_RFC_REQUEST("CloseRFCRequest"),
    @XmlEnumValue("GetRFCDetailRequest")
    GET_RFC_DETAIL_REQUEST("GetRFCDetailRequest"),
    @XmlEnumValue("GetRFCFulfillmentRequest")
    GET_RFC_FULFILLMENT_REQUEST("GetRFCFulfillmentRequest"),
    @XmlEnumValue("GetRFCNonFulfillmentRequest")
    GET_RFC_NON_FULFILLMENT_REQUEST("GetRFCNonFulfillmentRequest"),
    @XmlEnumValue("GetRFCAdviceRequest")
    GET_RFC_ADVICE_REQUEST("GetRFCAdviceRequest"),
    @XmlEnumValue("GetMyQueueRequest")
    GET_MY_QUEUE_REQUEST("GetMyQueueRequest"),
    @XmlEnumValue("SubmitFinancialReversalRequest")
    SUBMIT_FINANCIAL_REVERSAL_REQUEST("SubmitFinancialReversalRequest"),
    @XmlEnumValue("GetFinancialDetailRequest")
    GET_FINANCIAL_DETAIL_REQUEST("GetFinancialDetailRequest"),
    @XmlEnumValue("SubmitFraudReportRequest")
    SUBMIT_FRAUD_REPORT_REQUEST("SubmitFraudReportRequest"),
    @XmlEnumValue("FraudReportDetailsRequest")
    FRAUD_REPORT_DETAILS_REQUEST("FraudReportDetailsRequest"),
    @XmlEnumValue("SubmitFraudIgnoreRequest")
    SUBMIT_FRAUD_IGNORE_REQUEST("SubmitFraudIgnoreRequest"),
    @XmlEnumValue("SubmitExceptionRequest")
    SUBMIT_EXCEPTION_REQUEST("SubmitExceptionRequest"),
    @XmlEnumValue("InquiryExceptionRequest")
    INQUIRY_EXCEPTION_REQUEST("InquiryExceptionRequest"),
    @XmlEnumValue("ExceptionDetailsRequest")
    EXCEPTION_DETAILS_REQUEST("ExceptionDetailsRequest"),
    @XmlEnumValue("DisputeQuestionnaireRequest")
    DISPUTE_QUESTIONNAIRE_REQUEST("DisputeQuestionnaireRequest"),
    @XmlEnumValue("UploadImageRequest")
    UPLOAD_IMAGE_REQUEST("UploadImageRequest"),
    @XmlEnumValue("GetQuestionnaireDataRequest")
    GET_QUESTIONNAIRE_DATA_REQUEST("GetQuestionnaireDataRequest"),
    @XmlEnumValue("GetImageRequest")
    GET_IMAGE_REQUEST("GetImageRequest"),
    @XmlEnumValue("StopPaymentInquiryRequest")
    STOP_PAYMENT_INQUIRY_REQUEST("StopPaymentInquiryRequest"),
    @XmlEnumValue("StopPaymentOrderRequest")
    STOP_PAYMENT_ORDER_REQUEST("StopPaymentOrderRequest"),
    @XmlEnumValue("StopPaymentDetailsRequest")
    STOP_PAYMENT_DETAILS_REQUEST("StopPaymentDetailsRequest"),
    @XmlEnumValue("AccountingEntryRequest")
    ACCOUNTING_ENTRY_REQUEST("AccountingEntryRequest"),
    @XmlEnumValue("AccountingEntryDetailsRequest")
    ACCOUNTING_ENTRY_DETAILS_REQUEST("AccountingEntryDetailsRequest"),
    @XmlEnumValue("MiscFeeEntryRequest")
    MISC_FEE_ENTRY_REQUEST("MiscFeeEntryRequest"),
    @XmlEnumValue("MiscFeeDetailsRequest")
    MISC_FEE_DETAILS_REQUEST("MiscFeeDetailsRequest"),
    @XmlEnumValue("SubmitAdjustmentRequest")
    SUBMIT_ADJUSTMENT_REQUEST("SubmitAdjustmentRequest"),
    @XmlEnumValue("AdjustmentDetailsRequest")
    ADJUSTMENT_DETAILS_REQUEST("AdjustmentDetailsRequest"),
    @XmlEnumValue("ManualCaseCreationRequest")
    MANUAL_CASE_CREATION_REQUEST("ManualCaseCreationRequest"),
    @XmlEnumValue("SubmitTranInquiryRequest")
    SUBMIT_TRAN_INQUIRY_REQUEST("SubmitTranInquiryRequest"),
    @XmlEnumValue("GetTransInquiryResultsRequest")
    GET_TRANS_INQUIRY_RESULTS_REQUEST("GetTransInquiryResultsRequest"),
    @XmlEnumValue("GetTransDetailsRequest")
    GET_TRANS_DETAILS_REQUEST("GetTransDetailsRequest"),
    @XmlEnumValue("CreateCaseFromTransactionRequest")
    CREATE_CASE_FROM_TRANSACTION_REQUEST("CreateCaseFromTransactionRequest"),
    @XmlEnumValue("SetTransactionForCaseRequest")
    SET_TRANSACTION_FOR_CASE_REQUEST("SetTransactionForCaseRequest"),
    @XmlEnumValue("LinkUnlinkCasesRequest")
    LINK_UNLINK_CASES_REQUEST("LinkUnlinkCasesRequest"),
    @XmlEnumValue("IgnoreRejectRequest")
    IGNORE_REJECT_REQUEST("IgnoreRejectRequest"),
    @XmlEnumValue("GetMMIRequest")
    GET_MMI_REQUEST("GetMMIRequest"),
    @XmlEnumValue("GetTransactionsFromCaseRequest")
    GET_TRANSACTIONS_FROM_CASE_REQUEST("GetTransactionsFromCaseRequest"),
    @XmlEnumValue("GetEventTrackingVelocityTagsRequest")
    GET_EVENT_TRACKING_VELOCITY_TAGS_REQUEST("GetEventTrackingVelocityTagsRequest"),
    @XmlEnumValue("SubmitQuickFormRequest")
    SUBMIT_QUICK_FORM_REQUEST("SubmitQuickFormRequest"),
    @XmlEnumValue("GetVDASDetailsRequest")
    GET_VDAS_DETAILS_REQUEST("GetVDASDetailsRequest"),
    @XmlEnumValue("IgnoreVDASRequest")
    IGNORE_VDAS_REQUEST("IgnoreVDASRequest"),
    @XmlEnumValue("IgnoreReverseVDASRequest")
    IGNORE_REVERSE_VDAS_REQUEST("IgnoreReverseVDASRequest"),
    @XmlEnumValue("ViewPotentialQnMatchesRequest")
    VIEW_POTENTIAL_QN_MATCHES_REQUEST("ViewPotentialQnMatchesRequest"),
    @XmlEnumValue("ViewPotentialVDASMatchesRequest")
    VIEW_POTENTIAL_VDAS_MATCHES_REQUEST("ViewPotentialVDASMatchesRequest"),
    @XmlEnumValue("CloseMiscFeeRequest")
    CLOSE_MISC_FEE_REQUEST("CloseMiscFeeRequest"),
    @XmlEnumValue("CloseMessageRequest")
    CLOSE_MESSAGE_REQUEST("CloseMessageRequest"),
    @XmlEnumValue("RetrievePotentialMatchesRequest")
    RETRIEVE_POTENTIAL_MATCHES_REQUEST("RetrievePotentialMatchesRequest"),
    @XmlEnumValue("IgnoreUnmatchedItemRequest")
    IGNORE_UNMATCHED_ITEM_REQUEST("IgnoreUnmatchedItemRequest"),
    @XmlEnumValue("AddUnmatchedItemToCaseRequest")
    ADD_UNMATCHED_ITEM_TO_CASE_REQUEST("AddUnmatchedItemToCaseRequest"),
    @XmlEnumValue("LinkAsSameDisputeRequest")
    LINK_AS_SAME_DISPUTE_REQUEST("LinkAsSameDisputeRequest"),
    @XmlEnumValue("BatchQueueRequest")
    BATCH_QUEUE_REQUEST("BatchQueueRequest"),
    @XmlEnumValue("MarkBatchQueueItemAsReadRequest")
    MARK_BATCH_QUEUE_ITEM_AS_READ_REQUEST("MarkBatchQueueItemAsReadRequest"),
    @XmlEnumValue("ConfirmFraudReportRequest")
    CONFIRM_FRAUD_REPORT_REQUEST("ConfirmFraudReportRequest"),
    @XmlEnumValue("GetGMFPDetailsRequest")
    GET_GMFP_DETAILS_REQUEST("GetGMFPDetailsRequest"),
    @XmlEnumValue("UpdateGMFPStatusRequest")
    UPDATE_GMFP_STATUS_REQUEST("UpdateGMFPStatusRequest"),
    @XmlEnumValue("CreateMessageRequest")
    CREATE_MESSAGE_REQUEST("CreateMessageRequest"),
    @XmlEnumValue("UploadMessageImageRequest")
    UPLOAD_MESSAGE_IMAGE_REQUEST("UploadMessageImageRequest"),
    @XmlEnumValue("GetMessageRequest")
    GET_MESSAGE_REQUEST("GetMessageRequest"),
    @XmlEnumValue("GetMessageImageRequest")
    GET_MESSAGE_IMAGE_REQUEST("GetMessageImageRequest");
    private final String value;

    RequestNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestNameType fromValue(String v) {
        for (RequestNameType c: RequestNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
