//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RP_300_81 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RP_300_81">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.visa.com/ROLSI}RepreType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.visa.com/ROLSI}BaseDisputeGroup"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}AcqrCaseNum" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}AgentUniqueId" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ChargebackConditionNotMetInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ChargebackRemedyInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}CreditCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}CreditDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}CreditAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}CreditRefNum" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}FileIndCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ChargebackRefNum" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}MemberMsgEditText" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}RepresentmentMerchInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}MoreInfoComment" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}InternalRecordInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}TransactionReceiptInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}SignaturePINCVMEvidenceInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ReferralAuthorizationInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}EvidenceAccountNumberNotListedInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ParticipationRequestAndConsentFormInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}EvidencePINInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}AdditionalFnInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}MerchantIncludedCVV2InAuthReqInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}ProvidingCompellingEvidenceInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}CompellingEvidenceCategory" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}IPAddressInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}GeographicalLocationInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}DeviceIDOrDeviceNameInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}PurchaserNameAndEmailInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}WebsiteAccessedAfterTransactionDateInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}DeviceAndCardInUndisputedTransactionInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}VisaCardVerifiedByMerchantInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}CardholderNameMatchFlightManifestToItineraryInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visa.com/ROLSI}DigitalGoodsQualifiesForRepresentmentInd" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="createFinancial" type="{http://www.visa.com/ROLSI}YNType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RP_300_81")
public class RP30081
    extends RepreType
{


}
