//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTSIMiscFeeDetailsNewResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTSIMiscFeeDetailsNewResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="MiscFeeDetailsResponse" type="{http://www.visa.com/ROLSI}MiscFeeDetailsResponseType"/>
 *           &lt;element name="MiscFeeSwitchStatusResponse" type="{http://www.visa.com/ROLSI}MiscFeeSwitchStatusResponseType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTSIMiscFeeDetailsNewResponseType", propOrder = {
    "miscFeeDetailsResponse",
    "miscFeeSwitchStatusResponse"
})
public class RTSIMiscFeeDetailsNewResponseType {

    @XmlElement(name = "MiscFeeDetailsResponse")
    protected MiscFeeDetailsResponseType miscFeeDetailsResponse;
    @XmlElement(name = "MiscFeeSwitchStatusResponse")
    protected MiscFeeSwitchStatusResponseType miscFeeSwitchStatusResponse;

    /**
     * Gets the value of the miscFeeDetailsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MiscFeeDetailsResponseType }
     *     
     */
    public MiscFeeDetailsResponseType getMiscFeeDetailsResponse() {
        return miscFeeDetailsResponse;
    }

    /**
     * Sets the value of the miscFeeDetailsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscFeeDetailsResponseType }
     *     
     */
    public void setMiscFeeDetailsResponse(MiscFeeDetailsResponseType value) {
        this.miscFeeDetailsResponse = value;
    }

    /**
     * Gets the value of the miscFeeSwitchStatusResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MiscFeeSwitchStatusResponseType }
     *     
     */
    public MiscFeeSwitchStatusResponseType getMiscFeeSwitchStatusResponse() {
        return miscFeeSwitchStatusResponse;
    }

    /**
     * Sets the value of the miscFeeSwitchStatusResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscFeeSwitchStatusResponseType }
     *     
     */
    public void setMiscFeeSwitchStatusResponse(MiscFeeSwitchStatusResponseType value) {
        this.miscFeeSwitchStatusResponse = value;
    }

}
