//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.11.01 at 09:57:25 PM GMT
//

package io.github.brendonfm.visa.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(Include.NON_EMPTY)
public class SISubmitFraudReportRequestType extends RequestBodyType {

	@JsonProperty(value = "RequestHeader", required = true)
	protected RequestHeaderType requestHeader;
	@JsonProperty(value = "RequestData", required = true)
	protected RTSISubmitFraudReportType requestData;

	public SISubmitFraudReportRequestType() {
	}

	public SISubmitFraudReportRequestType(RequestHeaderType requestHeader, RTSISubmitFraudReportType requestData) {
		super();
		this.requestHeader = requestHeader;
		this.requestData = requestData;
	}

	/**
	 * Gets the value of the requestHeader property.
	 * 
	 * @return possible object is {@link RequestHeaderType }
	 */
	public RequestHeaderType getRequestHeader() {
		return requestHeader;
	}

	/**
	 * Sets the value of the requestHeader property.
	 * 
	 * @param value allowed object is {@link RequestHeaderType }
	 */
	public void setRequestHeader(final RequestHeaderType value) {
		this.requestHeader = value;
	}

	/**
	 * Gets the value of the requestData property.
	 * 
	 * @return possible object is {@link RTSISubmitFraudReportType }
	 */
	public RTSISubmitFraudReportType getRequestData() {
		return requestData;
	}

	/**
	 * Sets the value of the requestData property.
	 * 
	 * @param value allowed object is {@link RTSISubmitFraudReportType }
	 */
	public void setRequestData(final RTSISubmitFraudReportType value) {
		this.requestData = value;
	}

}
