//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SISubmitFinancialReversalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SISubmitFinancialReversalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FinancialReversalResponse" type="{http://www.visa.com/ROLSI}RTSIFinancialResponseType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SISubmitFinancialReversalType", propOrder = {
    "financialReversalResponse"
})
public class SISubmitFinancialReversalType {

    @XmlElement(name = "FinancialReversalResponse", required = true)
    protected RTSIFinancialResponseType financialReversalResponse;

    /**
     * Gets the value of the financialReversalResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIFinancialResponseType }
     *     
     */
    public RTSIFinancialResponseType getFinancialReversalResponse() {
        return financialReversalResponse;
    }

    /**
     * Sets the value of the financialReversalResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIFinancialResponseType }
     *     
     */
    public void setFinancialReversalResponse(RTSIFinancialResponseType value) {
        this.financialReversalResponse = value;
    }

}
