//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.11.01 at 09:57:25 PM GMT
//

package io.github.brendonfm.visa.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

public class StatusType {

	@JsonProperty(value = "Code", required = true)
	protected String code;
	@JsonProperty(value = "Message", required = true)
	protected String message;
	@JsonProperty(value = "ErrorIn")
	protected String errorIn;

	/**
	 * Gets the value of the code property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setCode(final String value) {
		this.code = value;
	}

	/**
	 * Gets the value of the message property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * Sets the value of the message property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setMessage(final String value) {
		this.message = value;
	}

	/**
	 * Gets the value of the errorIn property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getErrorIn() {
		return errorIn;
	}

	/**
	 * Sets the value of the errorIn property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setErrorIn(final String value) {
		this.errorIn = value;
	}

}
