//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TransIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransIDType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="ATRInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PIInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MMIInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransIDType", propOrder = {
    "value"
})
public class TransIDType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ATRInd")
    protected Boolean atrInd;
    @XmlAttribute(name = "PIInd")
    protected Boolean piInd;
    @XmlAttribute(name = "MMIInd")
    protected Boolean mmiInd;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the atrInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isATRInd() {
        return atrInd;
    }

    /**
     * Sets the value of the atrInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setATRInd(Boolean value) {
        this.atrInd = value;
    }

    /**
     * Gets the value of the piInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPIInd() {
        return piInd;
    }

    /**
     * Sets the value of the piInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPIInd(Boolean value) {
        this.piInd = value;
    }

    /**
     * Gets the value of the mmiInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMMIInd() {
        return mmiInd;
    }

    /**
     * Sets the value of the mmiInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMMIInd(Boolean value) {
        this.mmiInd = value;
    }

}
