//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateGMFPDetailsRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateGMFPDetailsRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}RequestBodyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="UpdateGMFPStatusRequest" type="{http://www.visa.com/ROLSI}UpdateGMFPDetailsType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateGMFPDetailsRequestType", propOrder = {
    "updateGMFPStatusRequest"
})
public class UpdateGMFPDetailsRequestType
    extends RequestBodyType
{

    @XmlElement(name = "UpdateGMFPStatusRequest")
    protected UpdateGMFPDetailsType updateGMFPStatusRequest;

    /**
     * Gets the value of the updateGMFPStatusRequest property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateGMFPDetailsType }
     *     
     */
    public UpdateGMFPDetailsType getUpdateGMFPStatusRequest() {
        return updateGMFPStatusRequest;
    }

    /**
     * Sets the value of the updateGMFPStatusRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateGMFPDetailsType }
     *     
     */
    public void setUpdateGMFPStatusRequest(UpdateGMFPDetailsType value) {
        this.updateGMFPStatusRequest = value;
    }

}
