//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 09:57:25 PM GMT 
//


package io.github.brendonfm.visa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VDASResponseBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VDASResponseBodyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visa.com/ROLSI}ResponseBodyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="GetVDASDetailsResponse" type="{http://www.visa.com/ROLSI}GetVDASDetailsResponseType"/>
 *           &lt;element name="IgnoreVDASResponse" type="{http://www.visa.com/ROLSI}IgnoreVDASResponseType"/>
 *           &lt;element name="IgnoreReverseVDASResponse" type="{http://www.visa.com/ROLSI}IgnoreReverseVDASResponseType"/>
 *           &lt;element name="ViewPotentialQnMatchesResponse" type="{http://www.visa.com/ROLSI}ViewPotentialQnMatchesResponseType"/>
 *           &lt;element name="ViewPotentialVDASMatchesResponse" type="{http://www.visa.com/ROLSI}ViewPotentialVDASMatchesResponseType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VDASResponseBodyType", propOrder = {
    "getVDASDetailsResponse",
    "ignoreVDASResponse",
    "ignoreReverseVDASResponse",
    "viewPotentialQnMatchesResponse",
    "viewPotentialVDASMatchesResponse"
})
public class VDASResponseBodyType
    extends ResponseBodyType
{

    @XmlElement(name = "GetVDASDetailsResponse")
    protected GetVDASDetailsResponseType getVDASDetailsResponse;
    @XmlElement(name = "IgnoreVDASResponse")
    protected IgnoreVDASResponseType ignoreVDASResponse;
    @XmlElement(name = "IgnoreReverseVDASResponse")
    protected IgnoreReverseVDASResponseType ignoreReverseVDASResponse;
    @XmlElement(name = "ViewPotentialQnMatchesResponse")
    protected ViewPotentialQnMatchesResponseType viewPotentialQnMatchesResponse;
    @XmlElement(name = "ViewPotentialVDASMatchesResponse")
    protected ViewPotentialVDASMatchesResponseType viewPotentialVDASMatchesResponse;

    /**
     * Gets the value of the getVDASDetailsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GetVDASDetailsResponseType }
     *     
     */
    public GetVDASDetailsResponseType getGetVDASDetailsResponse() {
        return getVDASDetailsResponse;
    }

    /**
     * Sets the value of the getVDASDetailsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetVDASDetailsResponseType }
     *     
     */
    public void setGetVDASDetailsResponse(GetVDASDetailsResponseType value) {
        this.getVDASDetailsResponse = value;
    }

    /**
     * Gets the value of the ignoreVDASResponse property.
     * 
     * @return
     *     possible object is
     *     {@link IgnoreVDASResponseType }
     *     
     */
    public IgnoreVDASResponseType getIgnoreVDASResponse() {
        return ignoreVDASResponse;
    }

    /**
     * Sets the value of the ignoreVDASResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link IgnoreVDASResponseType }
     *     
     */
    public void setIgnoreVDASResponse(IgnoreVDASResponseType value) {
        this.ignoreVDASResponse = value;
    }

    /**
     * Gets the value of the ignoreReverseVDASResponse property.
     * 
     * @return
     *     possible object is
     *     {@link IgnoreReverseVDASResponseType }
     *     
     */
    public IgnoreReverseVDASResponseType getIgnoreReverseVDASResponse() {
        return ignoreReverseVDASResponse;
    }

    /**
     * Sets the value of the ignoreReverseVDASResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link IgnoreReverseVDASResponseType }
     *     
     */
    public void setIgnoreReverseVDASResponse(IgnoreReverseVDASResponseType value) {
        this.ignoreReverseVDASResponse = value;
    }

    /**
     * Gets the value of the viewPotentialQnMatchesResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ViewPotentialQnMatchesResponseType }
     *     
     */
    public ViewPotentialQnMatchesResponseType getViewPotentialQnMatchesResponse() {
        return viewPotentialQnMatchesResponse;
    }

    /**
     * Sets the value of the viewPotentialQnMatchesResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewPotentialQnMatchesResponseType }
     *     
     */
    public void setViewPotentialQnMatchesResponse(ViewPotentialQnMatchesResponseType value) {
        this.viewPotentialQnMatchesResponse = value;
    }

    /**
     * Gets the value of the viewPotentialVDASMatchesResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ViewPotentialVDASMatchesResponseType }
     *     
     */
    public ViewPotentialVDASMatchesResponseType getViewPotentialVDASMatchesResponse() {
        return viewPotentialVDASMatchesResponse;
    }

    /**
     * Sets the value of the viewPotentialVDASMatchesResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewPotentialVDASMatchesResponseType }
     *     
     */
    public void setViewPotentialVDASMatchesResponse(ViewPotentialVDASMatchesResponseType value) {
        this.viewPotentialVDASMatchesResponse = value;
    }

}
